### ISSUE TITLE
ImportError: No module named HiveExtract (from HiveTransform.py)

### ISSUE THREAD

**Issue by richardxin** [linkedin/WhereHows#1026]
after unzipping the distribution file *.zip, I have following directory structure:

wherehows-backend
  |--bin (playbinary)
  |--conf
  |--jobs
  |--libs (jar files including wherehows-etl-wherehows-etl.jar)
  
  When I run backend binary from bin
  
  bin/playbinary, I saw this error in the log 
  
  2018-03-12 17:03:43 ERROR Job Launcher:91 - Traceback (most recent call last):
    File "<iostream>", line 23, in <module>
  ImportError: No module named HiveExtract

          at org.python.core.Py.ImportError(Py.java:328)
          at org.python.core.imp.import_first(imp.java:877)
          at org.python.core.imp.import_module_level(imp.java:972)
          at org.python.core.imp.importName(imp.java:1062)
          at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
          at org.python.core.PyObject.__call__(PyObject.java:431)
          at org.python.core.__builtin__.__import__(__builtin__.java:1232)
          at org.python.core.imp.importFromAs(imp.java:1156)
          at org.python.core.imp.importFrom(imp.java:1132)
          at org.python.pycode._pyx7.f$0(<iostream>:240)
          at org.python.pycode._pyx7.call_function(<iostream>)
          at org.python.core.PyTableCode.call(PyTableCode.java:167)
          at org.python.core.PyCode.call(PyCode.java:18)
          at org.python.core.Py.runCode(Py.java:1386)
          at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
          at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:291)
          at metadata.etl.dataset.hive.HiveMetadataEtl.transform(HiveMetadataEtl.java:56)
          at metadata.etl.EtlJob.run(EtlJob.java:180)
          at metadata.etl.Launcher.main(Launcher.java:86)
		  
this is the line that caused issue:
https://github.com/linkedin/WhereHows/blob/v1.0.0/wherehows-etl/src/main/resources/jython/HiveTransform.py#L23

After I copied HiveExtract.py to libs/, I'm no longer seeing the exception, what's the best practice to do this? do I have to copy all python scripts out to directory and set PYTHONPATH? (they are part of herehows-etl-wherehows-etl.jar now).

**Comment by richardxin** [comment]
weird, PySystem path in the log looks good to me:

2018-03-12 22:01:48 INFO  m.e.d.h.HiveMetadataEtl:178 - PySystem path: ['/opt/wherehows-backend/lib/Lib', '/opt/wherehows-backend/lib/org.python-jython-standalone-2.7.0.jar/Lib', '__classpath__', '__pyclasspath__/', '/opt/wherehows-backend/lib/wherehows-etl-wherehows-etl.jar/jython']

**Comment by yinsong** [comment]
i get the same error,how can i resolve it

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
