### ISSUE TITLE
build failed on windows 7(Resolved)

### ISSUE THREAD

**Issue by zhuxt2015** [linkedin/WhereHows#1097]
I was build success on centos 6.5,but get build failed on windows 7 OS.

```
gradlew.bat build

> Configure project :

> Task :wherehows-data-model:generateAvroJava
[WARNING] Avro: Invalid default for field state: null not a ["string"]
[WARNING] Avro: Invalid default for field state: null not a [{"type":"string","avro.java.string":"String"}]

> Task :wherehows-web:bowerInstall
bower bootstrap       extra-resolution Unnecessary resolution: bootstrap#3.3.7
bower jquery-ui       extra-resolution Unnecessary resolution: jquery-ui#^1.12.1

> Task :wherehows-web:emberBuild
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to dis
cover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.ro
ot }). Accessed from:   new NPMDependencyVersionChecker (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli-medium-editor\node_modules\ember-cli-version-checker\src\npm-dependency-version-
checker.js:11:33)

Running without permission to symlink will degrade build performance.
See http://ember-cli.com/user-guide/#windows for details.

bootstrap-sassy config: some JS loaded [dropdown,collapse,tab], glyphicons enabled
Cannot read property 'rootElement' of undefined


Stack Trace and Error Report: C:\%userpath%\AppData\Local\Temp/error.dump.26ddab58d5c57782209bddadadef98e9.log


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wherehows-web:emberBuild'.
> Process 'command 'D:\IdeaProjects\WhereHows\wherehows-web\build\nodejs\node-v8.9.4-win-x64\node.ex
e'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more l
og output.

BUILD FAILED in 18s
44 actionable tasks: 3 executed, 41 up-to-date

D:\IdeaProjects\WhereHows>
```

```
node v8.9.4
npm v5.8.0
```
How can I resolve the problem
Everyone can help me?

**Comment by zhuxt2015** [comment]
dump erro log 
```
=================================================================================

ENV Summary:

  TIME: Wed Apr 18 2018 14:58:07 GMT+0800 (中国标准时间)
  TITLE: ember
  ARGV:
  - D:\IdeaProjects\WhereHows\wherehows-web\build\nodejs\node-v8.9.4-win-x64\node.exe
  - D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\bin\ember
  - build
  - --environment
  - production
  EXEC_PATH: D:\IdeaProjects\WhereHows\wherehows-web\build\nodejs\node-v8.9.4-win-x64\node.exe
  TMPDIR: C:\Users\zhuxt\AppData\Local\Temp
  SHELL: null
  PATH:
  - D
  - \IdeaProjects\WhereHows\wherehows-web\build\nodejs\node-v8.9.4-win-x64;C
  - \Python27\;C
  - \Python27\Scripts;C
  - \ProgramData\Oracle\Java\javapath;C
  - \Windows\system32;C
  - \Windows;C
  - \Windows\System32\Wbem;C
  - \Windows\System32\WindowsPowerShell\v1.0\;C
  - \Program Files (x86)\NVIDIA Corporation\PhysX\Common;C
  - \Program Files\Git\cmd;D
  - \Program Files\Java\jdk1.8.0_121\bin;D
  - \Program Files\Java\jdk1.8.0_121\jre\bin;D
  - \Software\apache\apache-maven-3.3.9\bin;C
  - \Program Files\Intel\WiFi\bin\;C
  - \Program Files\Common Files\Intel\WirelessCommon\;C
  - \Go\bin;C
  - \Program Files (x86)\sbt\bin;C
  - \Program Files (x86)\scala\bin;D
  - \Software\apache\apache-ant-1.10.1\bin;C
  - \winutils\hadoop-2.6.0\bin;D
  - \Program Files\OpenVPN\bin;D
  - \Software\gradle-4.5\bin;C
  - \Program Files\nodejs\;D
  - \Software\activator-1.3.11-minimal\bin;D
  - \Software\phantomjs-2.1.1-windows\bin;C
  - \Users\zhuxt\AppData\Roaming\npm
  PLATFORM: win32 x64
  FREEMEM: 1975652352
  TOTALMEM: 16861478912
  UPTIME: 613918.8640782
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz - 2194
  - Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz - 2194
  - Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz - 2194
  - Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz - 2194
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 31.0.1
  - http_parser: 2.7.0
  - icu: 59.1
  - modules: 57
  - nghttp2: 1.25.0
  - node: 8.9.4
  - openssl: 1.0.2n
  - tz: 2017b
  - unicode: 9.0
  - uv: 1.15.0
  - v8: 6.1.534.50
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot read property 'rootElement' of undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot read property 'rootElement' of undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Cannot read property 'rootElement' of undefined
    at Class.config (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-tooltips\index.js:8:38)
    at addons.reduce (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\project.js:302:31)
    at Array.reduce (<anonymous>:null:null)
    at Project.getAddonsConfig (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\project.js:300:24)
    at Project.configWithoutCache (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\project.js:255:19)
    at Project.config (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\project.js:234:16)
    at Class.projectConfig (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli-htmlbars-inline-precompile\index.js:148:25)
    at Class.templateCompilerPath (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli-htmlbars-inline-precompile\index.js:153:23)
    at Class.included (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli-htmlbars-inline-precompile\index.js:62:39)
    at Class.superWrapper [as included] (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\core-object\lib\assign-properties.js:34:20)
    at addons.reduce (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\addon.js:405:26)
    at Array.reduce (<anonymous>:null:null)
    at Class.eachAddonInvoke (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\addon.js:402:24)
    at Class.included (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\addon.js:678:10)
    at Class.superWrapper [as included] (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\core-object\lib\assign-properties.js:34:20)
    at Class.included (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\@ember\test-helpers\index.js:20:26)
    at Class.superWrapper [as included] (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\core-object\lib\assign-properties.js:34:20)
    at addons.reduce (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\addon.js:405:26)
    at Array.reduce (<anonymous>:null:null)
    at Class.eachAddonInvoke (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\addon.js:402:24)
    at Class.included (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\addon.js:678:10)
    at Class.superWrapper [as included] (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\core-object\lib\assign-properties.js:34:20)
    at Class.included (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-qunit\index.js:17:26)
    at Class.superWrapper [as included] (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\core-object\lib\assign-properties.js:34:20)
    at addons.reduce (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\addon.js:405:26)
    at Array.reduce (<anonymous>:null:null)
    at Class.eachAddonInvoke (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\addon.js:402:24)
    at Class.included (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\addon.js:678:10)
    at Class.superWrapper [as included] (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\core-object\lib\assign-properties.js:34:20)
    at project.addons.project.addons.filter.addon (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\broccoli\ember-app.js:555:17)
    at Array.filter (<anonymous>:null:null)
    at EmberApp._notifyAddonIncluded (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\broccoli\ember-app.js:552:47)
    at new EmberApp (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\broccoli\ember-app.js:166:10)
    at module.exports (D:\IdeaProjects\WhereHows\wherehows-web\ember-cli-build.js:8:15)
    at Builder.setupBroccoliBuilder (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\builder.js:56:19)
    at new Builder (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\builder.js:30:10)
    at BuildTask.run (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\tasks\build.js:15:19)
    at Promise.resolve.then (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\command.js:243:46)
    at tryCatcher (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:323:19)
    at invokeCallback (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:495:31)
    at D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:559:14
    at flush (D:\IdeaProjects\WhereHows\wherehows-web\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:2402:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)


=================================================================================

```

**Comment by zhuxt2015** [comment]
I have resolved this issue!!

- 1.delete the old project, and clone a new project
- 2.put jar into wherehows-etl/extralibs
- 3.npm install  @ember-decorators/babel-transforms
- 4.modify broccoli_sass_compiler.js and ember.gradle file by reference https://hackmd.io/5TNL3spVSsOMSoHTHErHQQ?view#Fast-solution
- 5.gradlew.bat build.   

Good Luck

**Comment by EmnaDr** [comment]
Hello @zhuxt2015 
The above instructions didn't work for me :(

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
