### ISSUE TITLE
File "/WhereHows/wherehows-etl/build/libs/wherehows-etl.jar/jython/SchemaUrlHelper.py", line 17, in <module> java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.conf.Configuration

### ISSUE THREAD

**Issue by alidisi** [linkedin/WhereHows#1185]
how can i get the python script import the java package

java  -cp  /Users/chenwei/Documents/workspace/wherehows/1.0/WhereHows/wherehows-backend/build/libs/wherehows-backend.jar:/Users/chenwei/Documents/workspace/wherehows/1.0/WhereHows/wherehows-common/build/libs/wherehows-common.jar:/Users/chenwei/Documents/workspace/wherehows/1.0/WhereHows/wherehows-etl/build/libs/wherehows-etl.jar:/Users/chenwei/.ivy2/cache/org.slf4j/slf4j-api/jars/*:/Users/chenwei/Downloads/lombok-1.12.2.jar:/Users/chenwei/.ivy2/cache/org.slf4j/slf4j-simple/jars/*:/Users/chenwei/.gradle/caches/modules-2/files-2.1/org.python/jython-standalone/2.7.0/cdfb38bc6f8343bcf1d6accc2e1147e8e7b63b75/jython-standalone-2.7.0.jar:/Users/chenwei/.gradle/caches/modules-2/files-2.1/com.jcraft/jsch/0.1.54/da3584329a263616e277e15462b387addd1b208d/jsch-0.1.54.jar -Dconfig=/var/tmp/wherehows/hive/87/87.properties  -DCONTEXT=hive -Dlogback.configurationFile=/Users/chenwei/Documents/workspace/wherehows/WhereHows/wherehows-backend/conf/etl_logback.xml -DLOG_DIR=/var/tmp/wherehows/hive/87 wherehows.common.jobs.Launcher

[main] INFO metadata.etl.EtlJob - PySystem path: ['/Users/chenwei/.gradle/caches/modules-2/files-2.1/org.python/jython-standalone/2.7.0/cdfb38bc6f8343bcf1d6accc2e1147e8e7b63b75/Lib', '/Users/chenwei/.gradle/caches/modules-2/files-2.1/org.python/jython-standalone/2.7.0/cdfb38bc6f8343bcf1d6accc2e1147e8e7b63b75/jython-standalone-2.7.0.jar/Lib', '__classpath__', '__pyclasspath__/', '/Users/chenwei/Documents/workspace/wherehows/1.0/WhereHows/wherehows-etl/build/libs/wherehows-etl.jar/jython']
[main] INFO metadata.etl.dataset.hive.HiveMetadataEtl - In Hive metadata ETL, launch extract jython scripts
[main] ERROR wherehows.common.jobs.Launcher - Traceback (most recent call last):
  File "<iostream>", line 26, in <module>
  File "/Users/chenwei/Documents/workspace/wherehows/1.0/WhereHows/wherehows-etl/build/libs/wherehows-etl.jar/jython/SchemaUrlHelper.py", line 16, in <module>
ImportError: No module named apache

	at org.python.core.Py.ImportError(Py.java:328)
	at org.python.core.imp.import_logic(imp.java:912)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at SchemaUrlHelper$py.f$0(/Users/chenwei/Documents/workspace/wherehows/1.0/WhereHows/wherehows-etl/build/libs/wherehows-etl.jar/jython/SchemaUrlHelper.py:26)
	at SchemaUrlHelper$py.call_function(/Users/chenwei/Documents/workspace/wherehows/1.0/WhereHows/wherehows-etl/build/libs/wherehows-etl.jar/jython/SchemaUrlHelper.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.util.importer.importer_load_module(importer.java:109)
	at org.python.modules.zipimport.zipimporter.zipimporter_load_module(zipimporter.java:163)
	at org.python.modules.zipimport.zipimporter$zipimporter_load_module_exposer.__call__(Unknown Source)
	at org.python.core.PyBuiltinMethodNarrow.__call__(PyBuiltinMethodNarrow.java:46)
	at org.python.core.imp.loadFromLoader(imp.java:587)
	at org.python.core.imp.find_module(imp.java:537)
	at org.python.core.imp.import_next(imp.java:840)
	at org.python.core.imp.import_module_level(imp.java:959)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1081)
	at org.python.pycode._pyx0.f$0(<iostream>:545)
	at org.python.pycode._pyx0.call_function(<iostream>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:291)
	at metadata.etl.dataset.hive.HiveMetadataEtl.extract(HiveMetadataEtl.java:43)
	at metadata.etl.EtlJob.run(EtlJob.java:112)
	at wherehows.common.jobs.Launcher.main(Launcher.java:82)

**Comment by ankurgadgilwar** [comment]
Wasn't thios fixed after giving the path to the ConfigUtil.java file?

**Comment by alidisi** [comment]
no ,status can not find the right org.apache.hadoop.conf.Configuration after try hadoop-common-2.7.4.jar and hadoop-core-0.20.2.jar which have the org.apache.hadoop.conf.Configuration jar package
