### ISSUE TITLE
NumberFormatException related to LDAP port number

### ISSUE THREAD

**Issue by mmxmb** [linkedin/WhereHows#1200]
Here's my LDAP config in `.env`:

```
# LDAP
WHZ_LDAP_URL="ldap://host.corp.com:389"
WHZ_LDAP_PRINCIPAL_DOMAIN="@corp.com"
WHZ_LDAP_SEARCH_BASE="OU=Standard,OU=Client Users,DC=corp,DC=com"
```

After starting up the Docker image, I am able to navigate to `http://localhost:9001`. After I enter my credentials, I see the following error message in red letters below the login form:

```
<!DOCTYPE html> <html lang="en"> <head> <title>Error</title> <link rel="shortcut icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAlFJREFUeNqUU8tOFEEUPVVdNV3dPe8xYRBnjGhmBgKjKzCIiQvBoIaNbly5Z+PSv3Aj7DSiP2B0rwkLGVdGgxITSCRIJGSMEQWZR3eVt5sEFBgTb/dN1yvnnHtPNTPG4PqdHgCMXnPRSZrpSuH8vUJu4DE4rYHDGAZDX62BZttHqTiIayM3gGiXQsgYLEvATaqxU+dy1U13YXapXptpNHY8iwn8KyIAzm1KBdtRZWErpI5lEWTXp5Z/vHpZ3/wyKKwYGGOdAYwR0EZwoezTYApBEIObyELl/aE1/83cp40Pt5mxqCKrE4Ck+mVWKKcI5tA8BLEhRBKJLjez6a7MLq7XZtp+yyOawwCBtkiBVZDKzRk4NN7NQBMYPHiZDFhXY+p9ff7F961vVcnl4R5I2ykJ5XFN7Ab7Gc61VoipNBKF+PDyztu5lfrSLT/wIwCxq0CAGtXHZTzqR2jtwQiXONma6hHpj9sLT7YaPxfTXuZdBGA02Wi7FS48YiTfj+i2NhqtdhP5RC8mh2/Op7y0v6eAcWVLFT8D7kWX5S9mepp+C450MV6aWL1cGnvkxbwHtLW2B9AOkLeUd9KEDuh9fl/7CEj7YH5g+3r/lWfF9In7tPz6T4IIwBJOr1SJyIGQMZQbsh5P9uBq5VJtqHh2mo49pdw5WFoEwKWqWHacaWOjQXWGcifKo6vj5RGS6zykI587XeUIQDqJSmAp+lE4qt19W5P9o8+Lma5DcjsC8JiT607lMVkdqQ0Vyh3lHhmh52tfNy78ajXv0rgYzv8nfwswANuk+7sD/Q0aAAAAAElFTkSuQmCC"> <style> html, body, pre { margin: 0; padding: 0; font-family: Monaco, 'Lucida Console', monospace; background: #ECECEC; } h1 { margin: 0; background: #A31012; padding: 20px 45px; color: #fff; text-shadow: 1px 1px 1px rgba(0,0,0,.3); border-bottom: 1px solid #690000; font-size: 28px; } p#detail { margin: 0; padding: 15px 45px; background: #F5A0A0; border-top: 4px solid #D36D6D; color: #730000; text-shadow: 1px 1px 1px rgba(255,255,255,.3); font-size: 14px; border-bottom: 1px solid #BA7A7A; } </style> </head> <body> <h1>Oops, an error occurred</h1> <p id="detail"> This exception has been logged with id <strong>787272483</strong>. </p> </body> </html>
```

In the terminal where I launched Docker, I see the following error:

```
wherehows-frontend_1       | 2018-06-05 21:15:26 INFO  p.a.Play:97 - Application started (Prod)
wherehows-frontend_1       | 2018-06-05 21:15:26 INFO  p.c.s.NettyServer:165 - Listening for HTTP on /0.0.0.0:9000
wherehows-frontend_1       | 2018-06-05 21:15:30 INFO  application:94 - Creating DAO factory: wherehows.dao.DaoFactory
wherehows-frontend_1       | 2018-06-05 21:15:32 ERROR application:220 - Piwik site ID must be an integer
wherehows-frontend_1       | 2018-06-05 21:15:43 ERROR p.c.s.n.PlayDefaultUpstreamHandler:275 - Cannot invoke the action
wherehows-frontend_1       | java.lang.NumberFormatException: For input string: "389""
wherehows-frontend_1       | 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at com.sun.jndi.toolkit.url.Uri.parse(Uri.java:232) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at com.sun.jndi.toolkit.url.Uri.init(Uri.java:138) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapURL.<init>(LdapURL.java:82) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:163) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at javax.naming.InitialContext.init(InitialContext.java:244) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at javax.naming.InitialContext.<init>(InitialContext.java:216) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at security.AuthenticationManager.authenticateUser(AuthenticationManager.java:85) ~[wherehows-frontend.jar:na]
wherehows-frontend_1       | 	at controllers.Application.authenticate(Application.java:345) ~[wherehows-frontend.jar:na]
wherehows-frontend_1       | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$7$$anonfun$apply$7.apply(Routes.scala:3006) ~[wherehows-frontend.jar:na]
wherehows-frontend_1       | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$7$$anonfun$apply$7.apply(Routes.scala:3006) ~[wherehows-frontend.jar:na]
wherehows-frontend_1       | 	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.http.DefaultHttpRequestHandler$1.call(DefaultHttpRequestHandler.java:20) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70) ~[com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at play.core.j.JavaAction.apply(JavaAction.scala:94) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.Option.map(Option.scala:145) ~[org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537) ~[com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537) ~[com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
wherehows-frontend_1       | 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 2018-06-05 21:15:43 ERROR application:216 - 
wherehows-frontend_1       | 
wherehows-frontend_1       | ! @787272483 - Internal server error, for (POST) [/authenticate] ->
wherehows-frontend_1       |  
wherehows-frontend_1       | play.api.UnexpectedException: Unexpected exception[NumberFormatException: For input string: "389""]
wherehows-frontend_1       | 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:277) [com.typesafe.play-play-netty-server_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273) [com.typesafe.play-play-netty-server_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
wherehows-frontend_1       | 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | Caused by: java.lang.NumberFormatException: For input string: "389""
wherehows-frontend_1       | 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at com.sun.jndi.toolkit.url.Uri.parse(Uri.java:232) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at com.sun.jndi.toolkit.url.Uri.init(Uri.java:138) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapURL.<init>(LdapURL.java:82) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:163) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at javax.naming.InitialContext.init(InitialContext.java:244) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at javax.naming.InitialContext.<init>(InitialContext.java:216) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101) ~[na:1.8.0_171]
wherehows-frontend_1       | 	at security.AuthenticationManager.authenticateUser(AuthenticationManager.java:85) ~[wherehows-frontend.jar:na]
wherehows-frontend_1       | 	at controllers.Application.authenticate(Application.java:345) ~[wherehows-frontend.jar:na]
wherehows-frontend_1       | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$7$$anonfun$apply$7.apply(Routes.scala:3006) ~[wherehows-frontend.jar:na]
wherehows-frontend_1       | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$7$$anonfun$apply$7.apply(Routes.scala:3006) ~[wherehows-frontend.jar:na]
wherehows-frontend_1       | 	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.http.DefaultHttpRequestHandler$1.call(DefaultHttpRequestHandler.java:20) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70) [com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at play.core.j.JavaAction.apply(JavaAction.scala:94) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.Option.map(Option.scala:145) ~[org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[com.typesafe.play-play_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537) ~[com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537) ~[com.typesafe.play-play-iteratees_2.10-2.4.11.jar:2.4.11]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
wherehows-frontend_1       | 	... 6 common frames omitted
```

Because of the following line: 

```
play.api.UnexpectedException: Unexpected exception[NumberFormatException: For input string: "389""]
```

I suspect that something is wrong with my LDAP URL string but can't really pinpoint it.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team

**Comment by ruk91** [comment]
@mmxmb Did you fixed the issue?

**Comment by mmxmb** [comment]
@ruk91 no. I ended up not using this project
