### ISSUE TITLE
idea  java.lang.Exception: Process + -1 failed

### ISSUE THREAD

**Issue by 2804337402** [linkedin/WhereHows#1219]
2018-06-20 15:47:35 INFO  application:36 - on start---===
2018-06-20 15:47:35 INFO  p.a.Play:97 - Application started (Dev)
2018-06-20 15:47:35 INFO  application:49 - total 4 jobs due, white list : null
2018-06-20 15:47:35 INFO  application:55 - running job: job id :21
2018-06-20 15:47:35 INFO  application:74 - Current running jobs : 
2018-06-20 15:47:35 INFO  application:81 - Send message : (jobType:HIVE_DATASET_METADATA_ETL refIdType:DB refId: 61 whEtlJobId:  21 whEtlExecId:51336)
2018-06-20 15:47:35 INFO  application:55 - running job: job id :22
2018-06-20 15:47:35 DEBUG application:52 - run command : java -cp 'C:\Users\Administrator\.IntelliJIdea2017.2\config\plugins\Scala\launcher\sbt-launch.jar' -Dconfig=D:/workspace/idea_workspace/var/tmp/wherehows/exec/51336.properties -DCONTEXT=HIVE_DATASET_METADATA_ETL metadata.etl.Launcher
2018-06-20 15:47:35 INFO  application:74 - Current running jobs : 21	
2018-06-20 15:47:35 INFO  application:81 - Send message : (jobType:ORACLE_DATASET_METADATA_ETL refIdType:DB refId: 62 whEtlJobId:  22 whEtlExecId:51337)
2018-06-20 15:47:35 INFO  application:55 - running job: job id :23
2018-06-20 15:47:35 DEBUG application:52 - run command : java -cp 'C:\Users\Administrator\.IntelliJIdea2017.2\config\plugins\Scala\launcher\sbt-launch.jar' -Dconfig=D:/workspace/idea_workspace/var/tmp/wherehows/exec/51337.properties -DCONTEXT=ORACLE_DATASET_METADATA_ETL metadata.etl.Launcher
2018-06-20 15:47:35 INFO  application:74 - Current running jobs : 21	22	
2018-06-20 15:47:35 INFO  application:81 - Send message : (jobType:AZKABAN_LINEAGE_METADATA_ETL refIdType:APP refId: 64 whEtlJobId:  23 whEtlExecId:51338)
2018-06-20 15:47:35 INFO  application:55 - running job: job id :24
2018-06-20 15:47:35 DEBUG application:52 - run command : java -cp 'C:\Users\Administrator\.IntelliJIdea2017.2\config\plugins\Scala\launcher\sbt-launch.jar' -Dconfig=D:/workspace/idea_workspace/var/tmp/wherehows/exec/51338.properties -DCONTEXT=AZKABAN_LINEAGE_METADATA_ETL metadata.etl.Launcher
2018-06-20 15:47:35 INFO  application:74 - Current running jobs : 21	22	23	
2018-06-20 15:47:35 INFO  application:81 - Send message : (jobType:AZKABAN_EXECUTION_METADATA_ETL refIdType:APP refId: 65 whEtlJobId:  24 whEtlExecId:51339)
2018-06-20 15:47:35 DEBUG application:52 - run command : java -cp 'C:\Users\Administrator\.IntelliJIdea2017.2\config\plugins\Scala\launcher\sbt-launch.jar' -Dconfig=D:/workspace/idea_workspace/var/tmp/wherehows/exec/51339.properties -DCONTEXT=AZKABAN_EXECUTION_METADATA_ETL metadata.etl.Launcher
2018-06-20 15:47:35 ERROR application:97 - *** Process + -1 failed, status: 1
2018-06-20 15:47:35 ERROR application:98 - Error Details:
java.lang.Exception: Process + -1 failed
����: �Ҳ������޷��������� metadata.etl.Launcher

	at actors.EtlJobActor.onReceive(EtlJobActor.java:99)
2018-06-20 15:47:35 ERROR application:114 - ETL job (jobType:HIVE_DATASET_METADATA_ETL refIdType:DB refId: 61 whEtlJobId:  21 whEtlExecId:51336) got a problem
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
2018-06-20 15:47:35 ERROR application:97 - *** Process + -1 failed, status: 1
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
2018-06-20 15:47:35 ERROR application:98 - Error Details:
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
����: �Ҳ������޷��������� metadata.etl.Launcher
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)

	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
2018-06-20 15:47:35 ERROR application:114 - ETL job (jobType:AZKABAN_EXECUTION_METADATA_ETL refIdType:APP refId: 65 whEtlJobId:  24 whEtlExecId:51339) got a problem
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
java.lang.Exception: Process + -1 failed
	at actors.EtlJobActor.onReceive(EtlJobActor.java:99)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-06-20 15:47:35 ERROR application:97 - *** Process + -1 failed, status: 1
2018-06-20 15:47:35 ERROR application:98 - Error Details:
����: �Ҳ������޷��������� metadata.etl.Launcher

2018-06-20 15:47:35 ERROR application:114 - ETL job (jobType:ORACLE_DATASET_METADATA_ETL refIdType:DB refId: 62 whEtlJobId:  22 whEtlExecId:51337) got a problem
java.lang.Exception: Process + -1 failed
	at actors.EtlJobActor.onReceive(EtlJobActor.java:99)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
java.lang.Exception: Process + -1 failed
2018-06-20 15:47:36 ERROR application:97 - *** Process + -1 failed, status: 1
	at actors.EtlJobActor.onReceive(EtlJobActor.java:99)
2018-06-20 15:47:36 ERROR application:98 - Error Details:
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
����: �Ҳ������޷��������� metadata.etl.Launcher
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)

	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
2018-06-20 15:47:36 ERROR application:114 - ETL job (jobType:AZKABAN_LINEAGE_METADATA_ETL refIdType:APP refId: 64 whEtlJobId:  23 whEtlExecId:51338) got a problem
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by mtHuberty** [comment]
You need to locate the log file from that failed job. That will give you more specific error messages. I think my log files appeared in a directory somewhere underneath /application/logs/

**Comment by 2804337402** [comment]
![1529546000 1](https://user-images.githubusercontent.com/25359798/41693686-00f96c88-7539-11e8-904b-991fe913d195.jpg)

**Comment by 2804337402** [comment]
not  found  detail  logs  information

**Comment by 2804337402** [comment]
Idea is installed on Windows, not on Linux, does that matter?

**Comment by 2804337402** [comment]
![1529546616 1](https://user-images.githubusercontent.com/25359798/41694349-765aae30-753c-11e8-9259-9befad6ec23a.jpg)
![1529546738 1](https://user-images.githubusercontent.com/25359798/41694353-7aaf46e4-753c-11e8-9d54-cef69f4d7c25.jpg)
![1529546774 1](https://user-images.githubusercontent.com/25359798/41694355-7ef619b2-753c-11e8-9355-2cde8303b622.jpg)
![1529546944 1](https://user-images.githubusercontent.com/25359798/41694358-8398ab6a-753c-11e8-88aa-9ca3249074d9.jpg)
![1529546982 1](https://user-images.githubusercontent.com/25359798/41694362-863074fc-753c-11e8-925b-a33663573a06.jpg)
![1529547479 1](https://user-images.githubusercontent.com/25359798/41694363-881ab48a-753c-11e8-8e9c-7ca5ed7fe21b.jpg)

**Comment by 2804337402** [comment]
已解决

**Comment by wuangKKK** [comment]
> 解决

兄弟，你这个怎么解决的
