### ISSUE TITLE
Build failing. 

### ISSUE THREAD

**Issue by sabarnwa** [linkedin/WhereHows#1226]
Hi,
I am trying to build it on centos box, and running into following issue. Any idea how to fix this.

Gradle suite > Gradle test > wherehows.common.utils.JobsUtilTest.testGetScheduledJobs FAILED
   java.lang.AssertionError: expected [1] but found [24]
       at org.testng.Assert.fail(Assert.java:93)
       at org.testng.Assert.failNotEquals(Assert.java:512)
       at org.testng.Assert.assertEqualsImpl(Assert.java:134)
       at org.testng.Assert.assertEquals(Assert.java:115)
       at org.testng.Assert.assertEquals(Assert.java:388)
       at org.testng.Assert.assertEquals(Assert.java:398)
       at wherehows.common.utils.JobsUtilTest.testGetScheduledJobs(JobsUtilTest.java:67)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
       at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
       at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
       at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
       at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
       at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
       at org.testng.TestRunner.privateRun(TestRunner.java:744)
       at org.testng.TestRunner.run(TestRunner.java:602)
       at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
       at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
       at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
       at org.testng.SuiteRunner.run(SuiteRunner.java:289)
       at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
       at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
       at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
       at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
       at org.testng.TestNG.runSuites(TestNG.java:1144)
       at org.testng.TestNG.run(TestNG.java:1115)

Thanks,
Sakshi

**Comment by mtHuberty** [comment]
This failed for me too when I first started trying to use WhereHows and I couldn't end up solving it using the gradle build. I ended up using the Dockerized version (tag 1.0.0 specifically because the more recent version had another bug that I couldn't get past), and I've been able to progress that way.

**Comment by useracn** [comment]
Hello @mtHuberty , I used tag 1.0.0 for the dockerized version and was not able to launch the frontend. The build says it was successful, but the last 2 line says:  "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?". Also what should I use for the LDAP in .env file? im only using localhost for centos7.

Many thanks.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
