### ISSUE TITLE
LDAP Workaround or VM API Help

### ISSUE THREAD

**Issue by Calprice** [linkedin/WhereHows#1275]
Hi,

I am trying to setup WhereHows on my Mac and I've been having several issues doing so.

First, I tried setting it up locally with version 1.0.0. The backend, frontend, and elasticsearch were all configured properly, but I encountered problems when trying to login to the application. It required an LDAP server, however, I do not have an LDAP server and would very much rather not set one up. In a previous error raised (#616), someone mentioned using a chunk of SQL as a workaround:

INSERT INTO wherehows.users
(name, email, username, password_digest, password_digest_type, authentication_type)
VALUES
('test', 'test@email.com', 'test', SHA1('test'), 'SHA1', 'default')

Although the code ran successfully, I was still unable to successfully login to the wherehows app. Is there a different workaround for login?

After running into this error with LDAP, I tried setting up the virtual machine from version 0.2.1. I successfully installed the machine, ran the backend, and logged in to the UI. However, I have been unable to connect to my Hive metadata store. I carefully followed the instructions for setting up the metadata etl jobs (documentation I'm following: https://github.com/linkedin/WhereHows/wiki/Set-Up-New-Metadata-ETL-Jobs), but the listed API calls do not have the desired effect. This is my API call:

curl -H "Content-Type: application/json" -d '
{"db_id": 10001, 
"wh_etl_job_name": "HIVE_DATASET_METADATA_ETL", 
"ref_id": 3, "cron_expr": "0 30 0/6 * * ?", 
"properties": {"hive.metastore.username": "username", 
			"hive.metastore.password": "password", 
			"hive.metastore.jdbc.url": "url", 
			"hive.metastore.jdbc.driver": "driver"
			}, 
"encrypted_property_keys": null, 
"timeout": null, 
"next_run": null, 
"comments": "hive vm metadata etl"}' http://localhost:19001/etl -X POST

I had thought this would trigger the job to connect to the metadata store, but all it does is insert the properties into the wh_etl_job MySQL table, something I've already done manually in accordance with earlier documentation.

I'd really appreciate any help with either approach!

**Comment by mtHuberty** [comment]
I was able to use the SQL insert statement you found to successfully insert a user and then login on version 1.0.0.

In fact, our LDAP workaround is to read some user headers (we're behind an enterprise wide OAuth2, so we can be comfortably careless with trusting headers), then use basically that same SQL insert to create a new user in the wherehows mysql DB based on their headers, and then use their newly inserted DB info to automatically log them in. Took me a week of tinkering with the frontend files to get that working but it works great for us now.

All that to say, I would probably steer towards v1.0.0 and try the SQL again rather than going for 0.2.1. I've seen more unsolved issues on that earlier version than on 1.0.0.

Also in another issue they mentioned that the backend API is deprecated and not recommended for use, so maybe that's what's going wrong there. We had to make all of our jobs before deploying the backend by using the job templates that they provide. I can help you find those if needed!

You can also scp/ftp the job files from your local machine to your backend deployment while it's running and it will recognize them and fire them off. It seems to scrape the jobs/ folder for .job files every 5 minutes or so. To stop a job file, we usually just rename the file ending to ".stop" instead of deleting them.

**Comment by Calprice** [comment]
The insert statement runs successfully for me as well and I inserted several different users, but it still doesn't allow me to login. I did the following steps:
Run ElasticSearch
Run backend with command: ./gradlew wherehows-backend:runPlayBinary (successfully built, listening on port 19001)
Run frontend with command: ./gradlew wherehows-frontend:runPlayBinary (successfully built, listening on port 9000)

But then when I try to login with my previously-created user, I get this error log from the frontend:

ERROR a.a.ActorSystemImpl:66 - Uncaught fatal error from thread [application-akka.actor.default-dispatcher-4] shutting down ActorSystem [application]
java.lang.ExceptionInInitializerError: null
        at controllers.Application.authenticate(Application.java:382) ~[wherehows-frontend.jar:na]
        at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$7$$anonfun$apply$7.apply(Routes.scala:3006) ~[wherehows-frontend.jar:na]
        at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$7$$anonfun$apply$7.apply(Routes.scala:3006) ~[wherehows-frontend.jar:na]
        at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136) ~[play_2.10-2.4.11.jar:2.4.11]
        at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127) ~[play_2.10-2.4.11.jar:2.4.11]
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70) ~[play_2.10-2.4.11.jar:2.4.11]
        at play.http.DefaultHttpRequestHandler$1.call(DefaultHttpRequestHandler.java:20) ~[play_2.10-2.4.11.jar:2.4.11]
        at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) ~[play_2.10-2.4.11.jar:2.4.11]
        at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) ~[play_2.10-2.4.11.jar:2.4.11]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.10.5.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.10.5.jar:na]
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[play_2.10-2.4.11.jar:2.4.11]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70) ~[play-iteratees_2.10-2.4.11.jar:2.4.11]
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[play_2.10-2.4.11.jar:2.4.11]
        at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[scala-library-2.10.5.jar:na]
        at scala.concurrent.Future$.apply(Future.scala:485) ~[scala-library-2.10.5.jar:na]
        at play.core.j.JavaAction.apply(JavaAction.scala:94) ~[play_2.10-2.4.11.jar:2.4.11]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.10-2.4.11.jar:2.4.11]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.10-2.4.11.jar:2.4.11]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.10-2.4.11.jar:2.4.11]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[play_2.10-2.4.11.jar:2.4.11]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[play_2.10-2.4.11.jar:2.4.11]
        at scala.Option.map(Option.scala:145) ~[scala-library-2.10.5.jar:na]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[play_2.10-2.4.11.jar:2.4.11]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[play_2.10-2.4.11.jar:2.4.11]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[play-iteratees_2.10-2.4.11.jar:2.4.11]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[play-iteratees_2.10-2.4.11.jar:2.4.11]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[play-iteratees_2.10-2.4.11.jar:2.4.11]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[play-iteratees_2.10-2.4.11.jar:2.4.11]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537) ~[play-iteratees_2.10-2.4.11.jar:2.4.11]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537) ~[play-iteratees_2.10-2.4.11.jar:2.4.11]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.10.5.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.10.5.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) ~[akka-actor_2.10-2.3.13.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.10-2.3.13.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.10.5.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.10.5.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.10.5.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.10.5.jar:na]
Caused by: java.lang.NullPointerException: null
        at security.AuthenticationManager.<clinit>(AuthenticationManager.java:60) ~[wherehows-frontend.jar:na]
        ... 39 common frames omitted
[ERROR] [07/31/2018 08:49:09.539] [application-akka.actor.default-dispatcher-13] [ActorSystem(application)] Uncaught fatal error from thread [application-akka.actor.default-dispatcher-13] shutting down ActorSystem [application]
java.lang.NoClassDefFoundError: Could not initialize class security.AuthenticationManager
        at controllers.Application.authenticate(Application.java:382)
        at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$7$$anonfun$apply$7.apply(Routes.scala:3006)
        at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$7$$anonfun$apply$7.apply(Routes.scala:3006)
        at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136)
        at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127)
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70)
        at play.http.DefaultHttpRequestHandler$1.call(DefaultHttpRequestHandler.java:20)
        at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94)
        at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
        at scala.concurrent.impl.Future$.apply(Future.scala:31)
        at scala.concurrent.Future$.apply(Future.scala:485)
        at play.core.j.JavaAction.apply(JavaAction.scala:94)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
        at scala.Option.map(Option.scala:145)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

#694 had the same problem as I, but I can't seem to get the workaround solution to function. Is there some extra step necessary to connect the application to the mysql database?

**Comment by mtHuberty** [comment]
When the frontend and backend start, I believe they immediately begin looking for a connection on port 3306 to the MySQL DB. I think they eventually timeout after a couple minutes if they can't connect.

I'm going off memory here as it's been awhile since I've checked the logs. I use the Docker builds and the logging is handled by docker-compose, but I'm sure there's logging happening somewhere on the pure gradle builds too. Have you been able to locate the log output that occurs when the front/backend start up? Mine look like this:
```
2018/07/30 19:22:40 Waiting for: tcp://localhost:3306
2018/07/30 19:22:40 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:41 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:42 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:43 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:44 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:45 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:46 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:47 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:48 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:49 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:50 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:51 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:52 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:53 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:54 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:55 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:56 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:57 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:58 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:22:59 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:23:00 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:23:01 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:23:02 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:23:03 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:23:04 Problem with dial: dial tcp [::1]:3306: getsockopt: connection refused. Sleeping 1s
2018/07/30 19:23:05 Connected to tcp://localhost:3306
NettyServer.main is deprecated. Please start your Play server with the ${ProdServerStart.getClass.getName}.main.
2018-07-30 19:23:07 INFO  application:55 - Creating Pool for datasource 'wherehows'
2018-07-30 19:23:08 INFO  p.a.d.DefaultDBApi:45 - Database [wherehows] connected at jdbc:mysql://localhost:3306/wherehows
2018-07-30 19:23:08 INFO  application:34 - on start---===
2018-07-30 19:23:08 INFO  p.a.Play:97 - Application started (Prod)
2018-07-30 19:23:08 INFO  application:67 - Enabled jobs: []
2018-07-30 19:23:08 INFO  application:70 - Scheduled jobs: {}
2018-07-30 19:23:08 INFO  p.c.s.NettyServer:165 - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
```

**Comment by jywadhwani** [comment]
We have pushed a change that permits other authentication methods (not necessarily LDAP) using JAAS config. Relevant PR https://github.com/linkedin/WhereHows/pull/1280

Hope this helps!

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
