### ISSUE TITLE
Unable to see all the flows in flow screen

### ISSUE THREAD

**Issue by kiranclarivate** [linkedin/WhereHows#1277]
Hi,

I can see only 1 flow in the flow list screen.I checked that backend query gives out 10 flows , but frontend is showing only the last flow in the screen .. http://localhost:9000/#/browse/flows
Could you please help?

Thanks,
Kiran

**Comment by jimmy-src** [comment]
the same to me.How to resolve this?

AZKABAN_LINEAGE_METADATA_ETL

```
2018-10-11 17:23:34 INFO  m.e.l.AzJobChecker:108 - Get recent flow sql : select exec_id, flow_id, status, submit_user, flow_data from execution_flows where end_time > 1539244414492 and end_time < 1539249814492
2018-10-11 17:23:35 INFO  m.e.l.AzLineageExtractorMaster:81 - Total number of azkaban jobs : 347
2018-10-11 17:23:35 ERROR Job Launcher:91 - java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460)
	at java.util.Properties.setProperty(Properties.java:166)
	at java.lang.System.setProperty(System.java:796)
	at metadata.etl.lineage.HadoopJobHistoryNodeExtractor.<init>(HadoopJobHistoryNodeExtractor.java:71)
	at metadata.etl.lineage.AzLineageExtractorMaster.run(AzLineageExtractorMaster.java:91)
	at metadata.etl.lineage.AzLineageExtractorMaster.run(AzLineageExtractorMaster.java:65)
	at metadata.etl.lineage.AzLineageMetadataEtl.extract(AzLineageMetadataEtl.java:88)
	at metadata.etl.EtlJob.run(EtlJob.java:179)
	at metadata.etl.Launcher.main(Launcher.java:86)

```

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
