### ISSUE TITLE
LDAP auth

### ISSUE THREAD

**Issue by djKooks** [linkedin/WhereHows#1282]
Hello
I started on looking, and success running front-end part, but found some error in log:
```
2018-07-31 19:12:30 INFO  p.a.Play:97 - Application started (Dev)
2018-07-31 19:12:31 INFO  application:118 - Creating DAO factory: wherehows.dao.DaoFactory
2018-07-31 19:12:34 ERROR application:263 - Piwik site ID must be an integer
2018-07-31 19:12:34 ERROR application:216 - 

! @78mg3mlg5 - Internal server error, for (GET) [/api/v1/party/entities] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT DISTINCT user_id as id, display_name as name, 'person' as category FROM dir_external_user_info WHERE is_active = 'Y' and org_hierarchy_depth > 1 UNION SELECT DISTINCT group_id as id, NULL as name, 'group' as category FROM dir_external_group_user_map WHERE group_id > '']; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'wherehows.dir_external_user_info' doesn't exist]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.10-2.4.11.jar:2.4.11]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.10-2.4.11.jar:2.4.11]
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.10-2.4.11.jar:2.4.11]
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.10-2.4.11.jar:2.4.11]
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.10-2.4.11.jar:2.4.11]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [play-netty-server_2.10-2.4.11.jar:2.4.11]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:159) [play-netty-server_2.10-2.4.11.jar:2.4.11]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library-2.10.5.jar:na]
        at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library-2.10.5.jar:na]
        at scala.util.Try$.apply(Try.scala:161) [scala-library-2.10.5.jar:na]
        at scala.util.Failure.recover(Try.scala:185) [scala-library-2.10.5.jar:na]
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.10.5.jar:na]
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.10.5.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.10.5.jar:na]
        at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.10-2.4.11.jar:2.4.11]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.10-2.4.11.jar:2.4.11]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.10.5.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.10.5.jar:na]
```
Is there something I missed?

**Comment by djKooks** [comment]
I just tried again with docker, but found other problem:
```
wherehows-frontend_1       |    at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:259) ~[org.hibernate-hibernate-core-5.2.16.Final.jar:5.2.16.Final]
wherehows-frontend_1       |    ... 52 common frames omitted
wherehows-frontend_1       | Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure
wherehows-frontend_1       | 
wherehows-frontend_1       | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
wherehows-frontend_1       |    at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:569) ~[com.zaxxer-HikariCP-2.7.8.jar:na]
wherehows-frontend_1       |    at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:555) ~[com.zaxxer-HikariCP-2.7.8.jar:na]
wherehows-frontend_1       |    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[com.zaxxer-HikariCP-2.7.8.jar:na]
wherehows-frontend_1       |    at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[com.zaxxer-HikariCP-2.7.8.jar:na]
wherehows-frontend_1       |    at com.zaxxer.hikari.hibernate.HikariConnectionProvider.configure(HikariConnectionProvider.java:87) ~[com.zaxxer-HikariCP-2.7.8.jar:na]
wherehows-frontend_1       |    ... 60 common frames omitted
wherehows-frontend_1       | Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
wherehows-frontend_1       | 
wherehows-frontend_1       | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
wherehows-frontend_1       |    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_171]
wherehows-frontend_1       |    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_171]
wherehows-frontend_1       |    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_171]
wherehows-frontend_1       |    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_171]
wherehows-frontend_1       |    at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       |    at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       |    at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       |    at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       |    at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2222) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       |    at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2017) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       |    at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       |    at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       |    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_171]
wherehows-frontend_1       |    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_171]
wherehows-frontend_1       |    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_171]
wherehows-frontend_1       |    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_171]
wherehows-frontend_1       |    at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       |    at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       |    at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       |    at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:428) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       |    at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:136) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       |    at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:107) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       |    at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365) ~[com.zaxxer-HikariCP-2.7.8.jar:na]
wherehows-frontend_1       |    at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194) ~[com.zaxxer-HikariCP-2.7.8.jar:na]
wherehows-frontend_1       |    at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460) ~[com.zaxxer-HikariCP-2.7.8.jar:na]
wherehows-frontend_1       |    at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:534) ~[com.zaxxer-HikariCP-2.7.8.jar:na]
wherehows-frontend_1       |    ... 63 common frames omitted
wherehows-frontend_1       | Caused by: java.net.ConnectException: Connection refused (Connection refused)
wherehows-frontend_1       |    at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_171]
wherehows-frontend_1       |    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_171]
wherehows-frontend_1       |    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_171]
wherehows-frontend_1       |    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_171]
wherehows-frontend_1       |    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_171]
wherehows-frontend_1       |    at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_171]
wherehows-frontend_1       |    at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       |    at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300) ~[mysql-mysql-connector-java-5.1.44.jar:5.1.44]
wherehows-frontend_1       |    ... 82 common frames omitted
```
Hope you could find something...

**Comment by djKooks** [comment]
Sorry for confused. The problem above was my mistake while setting SQL tables...
Now it has been set, but it causes error with authentication.
```
Waiting for changes to input files of tasks... (ctrl-d to exit)
2018-08-02 10:25:33 ERROR application:263 - Piwik site ID must be an integer
2018-08-02 10:26:22 WARN  application:101 - Ldap authentication error for: wherehows - your_ldap_url : javax.naming.NamingException: Cannot parse url: your_ldap_url [Root exception is java.net.MalformedURLException: Invalid URI: your_ldap_url]
2018-08-02 10:26:22 WARN  application:390 - Authentication error!
javax.naming.AuthenticationException: javax.naming.NamingException: Cannot parse url: your_ldap_url [Root exception is java.net.MalformedURLException: Invalid URI: your_ldap_url]
```
I didn't set anything with LDAP. Is it necessary to setup LDAP for login?

**Comment by jywadhwani** [comment]
@djKooks it's not necessary for you to set up LDAP. You are free to use any other authentication method/module in jaas config (relevant PR https://github.com/linkedin/WhereHows/pull/1280). Hope this helps!

**Comment by djKooks** [comment]
@jywadhwani thanks! Is there a guide for jaas config, or reference I could refer? Sorry that I'm not good in this part...

**Comment by jywadhwani** [comment]
Jaas wiki: https://docs.oracle.com/javase/8/docs/technotes/guides/security/jaas/JAASRefGuide.html.  LDAPLoginModule: https://docs.oracle.com/javase/8/docs/jre/api/security/jaas/spec/com/sun/security/auth/module/LdapLoginModule.html.

**Comment by jywadhwani** [comment]
@djKooks you could try using dummy authentication for now that authenticates against any password (just that the username should be present in the users table). The new version of jaas config is configured to consider this form of authentication as well.

**Comment by djKooks** [comment]
@jywadhwani thanks! Do you mean user table loaded in mysql db?

**Comment by alyiwang** [comment]
@djKooks  Yes, the "users" table in mysql DB
