### ISSUE TITLE
After starting docker-composer up, frontend continer is not running iam getting below error. 

### ISSUE THREAD

**Issue by pradheep2005** [linkedin/WhereHows#1332]
Hello Team,

After starting docker-composer up, frontend container is not running. iam getting below error. Please help us

NettyServer.main is deprecated. Please start your Play server with the ${ProdServerStart.getClass.getName}.main.
Some(ConfigOrigin(application.conf @ jar:file:/application/lib/wherehows-frontend.jar!/application.conf))
Oops, cannot start the server.
Configuration error: Configuration error[application.conf @ jar:file:/application/lib/wherehows-frontend.jar!/application.conf: 82: Could not resolve substitution to a value: ${WHZ_LDAP_PRINCIPAL_DOMAIN}]
        at play.api.Configuration$.configError(Configuration.scala:180)
        at play.api.Configuration$.load(Configuration.scala:103)
        at play.core.server.ProdServerStart$.readServerConfigSettings(ProdServerStart.scala:81)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:42)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
        at play.core.server.NettyServer$.main(NettyServer.scala:232)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: com.typesafe.config.ConfigException$UnresolvedSubstitution: application.conf @ jar:file:/application/lib/wherehows-frontend.jar!/application.conf: 82: Could not resolve substitution to a value: ${WHZ_LDAP_PRINCIPAL_DOMAIN}
        at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:108)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:231)
        at com.typesafe.config.impl.SimpleConfig.resolveWith(SimpleConfig.java:74)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:64)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:59)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:37)
        at play.api.Configuration$.load(Configuration.scala:99)
        ... 5 more
2018/08/21 06:53:20 Command exited with error: exit status 255
2018/08/21 07:02:55 Waiting for: tcp://wherehows-mysql:3306
2018/08/21 07:02:55 Waiting for: http://wherehows-elasticsearch:9200
2018/08/21 07:02:55 Connected to tcp://wherehows-mysql:3306
2018/08/21 07:02:55 Received 200 from http://wherehows-elasticsearch:9200
NettyServer.main is deprecated. Please start your Play server with the ${ProdServerStart.getClass.getName}.main.
Some(ConfigOrigin(application.conf @ jar:file:/application/lib/wherehows-frontend.jar!/application.conf))
Oops, cannot start the server.
Configuration error: Configuration error[application.conf @ jar:file:/application/lib/wherehows-frontend.jar!/application.conf: 82: Could not resolve substitution to a value: ${WHZ_LDAP_PRINCIPAL_DOMAIN}]
        at play.api.Configuration$.configError(Configuration.scala:180)
        at play.api.Configuration$.load(Configuration.scala:103)
        at play.core.server.ProdServerStart$.readServerConfigSettings(ProdServerStart.scala:81)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:42)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
        at play.core.server.NettyServer$.main(NettyServer.scala:232)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: com.typesafe.config.ConfigException$UnresolvedSubstitution: application.conf @ jar:file:/application/lib/wherehows-frontend.jar!/application.conf: 82: Could not resolve substitution to a value: ${WHZ_LDAP_PRINCIPAL_DOMAIN}
        at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:108)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:231)
        at com.typesafe.config.impl.SimpleConfig.resolveWith(SimpleConfig.java:74)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:64)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:59)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:37)
        at play.api.Configuration$.load(Configuration.scala:99)
        ... 5 more

**Comment by Refa90** [comment]
I encounter the same issue, yet unresolved

**Comment by mfueser** [comment]
Same here, cannot get it working...

**Comment by FisherYu0112** [comment]
i also encounter this issue. And it was working with version v1.1.0, maybe the docker was built with this version,  so the configuration files and enviroment variables are pre-defined for v1.1.0

**Comment by mobiustech** [comment]
Anybody found a resolution to this?

**Comment by tkollo** [comment]
Still does not work...

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
