### ISSUE TITLE
登录之后报错，页面上什么也没有

### ISSUE THREAD

**Issue by wuchenlv1988** [linkedin/WhereHows#1393]
play.api.UnexpectedException: Unexpected exception[UnsupportedOperationException: Operation not implemented]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [com.typesafe.play-play-netty-server_2.11-2.4.11.jar:2.4.11]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:159) [com.typesafe.play-play-netty-server_2.11-2.4.11.jar:2.4.11]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang-scala-library-2.11.6.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) [org.scala-lang-scala-library-2.11.6.jar:na]
	at scala.util.Try$.apply(Try.scala:191) [org.scala-lang-scala-library-2.11.6.jar:na]
	at scala.util.Failure.recover(Try.scala:215) [org.scala-lang-scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang-scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang-scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang-scala-library-2.11.6.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [com.typesafe.play-play-iteratees_2.11-2.4.11.jar:2.4.11]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [com.typesafe.play-play-iteratees_2.11-2.4.11.jar:2.4.11]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang-scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang-scala-library-2.11.6.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang-scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang-scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang-scala-library-2.11.6.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) [com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka-akka-actor_2.11-2.3.13.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka-akka-actor_2.11-2.3.13.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang-scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang-scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang-scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang-scala-library-2.11.6.jar:na]
Caused by: java.lang.UnsupportedOperationException: Operation not implemented
	at wherehows.dao.view.DataTypesViewDao.getAllPlatforms(DataTypesViewDao.java:38) ~[wherehows-dao-wherehows-dao.jar:na]
	at controllers.api.v2.Dataset.lambda$listSegments$1(Dataset.java:96) ~[wherehows-frontend.jar:na]
	at play.core.j.FPromiseHelper$$anonfun$promise$2.apply(FPromiseHelper.scala:36) ~[com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang-scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang-scala-library-2.11.6.jar:na]
	... 7 common frames omitted

**Comment by tonglin0325** [comment]
我也遇到类似的问题
2018-09-18 19:37:59 ERROR application:216 - 

! @79a8nc8l0 - Internal server error, for (GET) [/api/v2/platforms] ->
 
play.api.UnexpectedException: Unexpected exception[UnsupportedOperationException: Operation not implemented]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play-play_2.11-2.4.11.jar:2.4.11]

**Comment by cgf120** [comment]
some code no impl

**Comment by tonglin0325** [comment]
可能是v1.1.0版本的问题,可以看一下issue 1131 @cgf120 @wuchenlv1988

**Comment by jimmy-src** [comment]
回退到v1.0.0版本就ok

#1457 

加微信群讨论

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
