### ISSUE TITLE
etl jobs run failed

### ISSUE THREAD

**Issue by tonglin0325** [linkedin/WhereHows#1399]
I try to config hdfs and hive etl jobs,but run failed

2018-09-20 20:38:25 INFO  application:61 - Enabled jobs: [HDFS_METADATA_ETL, HIVE_METADATA_ETL]
2018-09-20 20:38:25 INFO  application:64 - Scheduled jobs: {APPWORX_EXECUTION_METADATA_ETL=1537362600, DRUID_METADATA_ETL=1537326600, ORACLE_METADATA_ETL=1537428600, AZKABAN_LINEAGE_METADATA_ETL=1537359000, UMP_METRIC_ETL=1537329600, APPWORX_LINEAGE_METADATA_ETL=1537363500, LDAP_USER_ETL=1537372800, HDFS_METADATA_ETL=1537446840, AZKABAN_EXECUTION_METADATA_ETL=1537360200, TERADATA_METADATA_ETL=1537390800, HIVE_METADATA_ETL=1537446840, OOZIE_EXECUTION_METADATA_ETL=1537360200}
2018-09-20 20:38:25 INFO  application:82 - Running job: HDFS_METADATA_ETL
2018-09-20 20:38:25 INFO  application:91 - Current running jobs : 
2018-09-20 20:38:25 INFO  application:98 - Send message : (jobName:HDFS_METADATA_ETL, whEtlExecId:251)
2018-09-20 20:38:25 DEBUG application:72 - run command : [java, -cp, /home/lintong/coding/java/WhereHows/wherehows-backend/build/stage/wherehows-backend/lib/wherehows-backend.jar, -Dconfig=/var/tmp/wherehows/exec/251.properties, -DCONTEXT=HDFS_METADATA_ETL, -Dlogback.configurationFile=etl_logback.xml, -DLOG_DIR=/var/tmp/wherehows, metadata.etl.Launcher] ; timeout: 3000
2018-09-20 20:38:25 INFO  application:82 - Running job: HIVE_METADATA_ETL
2018-09-20 20:38:25 INFO  application:91 - Current running jobs : HDFS_METADATA_ETL	
2018-09-20 20:38:25 INFO  application:98 - Send message : (jobName:HIVE_METADATA_ETL, whEtlExecId:252)
2018-09-20 20:38:25 DEBUG application:72 - run command : [java, -cp, /home/lintong/coding/java/WhereHows/wherehows-backend/build/stage/wherehows-backend/lib/wherehows-backend.jar, -Dconfig=/var/tmp/wherehows/exec/252.properties, -DCONTEXT=HIVE_METADATA_ETL, -Dlogback.configurationFile=etl_logback.xml, -DLOG_DIR=/var/tmp/wherehows, metadata.etl.Launcher] ; timeout: 12000
2018-09-20 20:38:30 ERROR application:121 - *** Process + 23130 failed, status: 1
2018-09-20 20:38:30 ERROR application:122 - Error Details:

java.lang.Exception: Process + 23130 failed
	at actors.EtlJobActor.onReceive(EtlJobActor.java:123)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-09-20 20:38:30 ERROR application:138 - ETL job (jobName:HDFS_METADATA_ETL, whEtlExecId:251) got a problem
2018-09-20 20:38:31 ERROR application:121 - *** Process + 23134 failed, status: 1
2018-09-20 20:38:31 ERROR application:122 - Error Details:

java.lang.Exception: Process + 23134 failed
	at actors.EtlJobActor.onReceive(EtlJobActor.java:123)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-09-20 20:38:31 ERROR application:138 - ETL job (jobName:HIVE_METADATA_ETL, whEtlExecId:252) got a problem

and hdfs_raw_metadata.json.log shows

SchemaFetch begins
Exception in thread "main" java.lang.IllegalArgumentException: Can't get Kerberos realm
	at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:65)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:305)
	at org.apache.hadoop.security.UserGroupInformation.setConfiguration(UserGroupInformation.java:351)
	at wherehows.SchemaFetch.<init>(SchemaFetch.java:82)
	at wherehows.SchemaFetch.main(SchemaFetch.java:335)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:239)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:153)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.security.authentication.util.KerberosUtil.getDefaultRealm(KerberosUtil.java:110)
	at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:63)
	... 10 more
Caused by: KrbException: Cannot locate default realm
	at sun.security.krb5.Config.getDefaultRealm(Config.java:1029)
	... 16 more

**Comment by jimmy-src** [comment]
你的集群启用了kerberos吧，kerberos可能配置不对
```
kerberos.auth=False
kerberos.keytab.file=
kerberos.principal=

krb5.kdc=
krb5.realm=
```

#1457

加微信群讨论

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
