### ISSUE TITLE
Caused by: java.lang.NullPointerException: scheme

### ISSUE THREAD

**Issue by tonglin0325** [linkedin/WhereHows#1409]
wherehows-frontend meet some problems:

2018-09-24 16:48:28 ERROR application:216 - 

! @79bphgb6h - Internal server error, for (GET) [/api/v1/search?keyword=undefined&category=datasets&page=1&source=all] ->
 
play.api.UnexpectedException: Unexpected exception[NullPointerException: scheme]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [com.typesafe.play-play-netty-server_2.10-2.4.8.jar:2.4.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:159) [com.typesafe.play-play-netty-server_2.10-2.4.8.jar:2.4.8]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.util.Try$.apply(Try.scala:161) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.util.Failure.recover(Try.scala:185) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang-scala-library-2.10.5.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [com.typesafe.play-play-iteratees_2.10-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [com.typesafe.play-play-iteratees_2.10-2.4.8.jar:2.4.8]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang-scala-library-2.10.5.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka-akka-actor_2.10-2.3.13.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang-scala-library-2.10.5.jar:na]
Caused by: java.lang.NullPointerException: scheme
	at com.ning.http.client.uri.Uri.<init>(Uri.java:56) ~[com.ning-async-http-client-1.9.36.jar:na]
	at com.ning.http.client.uri.Uri.create(Uri.java:32) ~[com.ning-async-http-client-1.9.36.jar:na]
	at com.ning.http.client.uri.Uri.create(Uri.java:25) ~[com.ning-async-http-client-1.9.36.jar:na]
	at com.ning.http.client.RequestBuilderBase.setUrl(RequestBuilderBase.java:307) ~[com.ning-async-http-client-1.9.36.jar:na]
	at com.ning.http.client.RequestBuilder.setUrl(RequestBuilder.java:165) ~[com.ning-async-http-client-1.9.36.jar:na]
	at play.libs.ws.ning.NingWSRequest.buildRequest(NingWSRequest.java:401) ~[com.typesafe.play-play-java-ws_2.10-2.4.8.jar:2.4.8]
	at play.libs.ws.ning.NingWSRequest.execute(NingWSRequest.java:394) ~[com.typesafe.play-play-java-ws_2.10-2.4.8.jar:2.4.8]
	at play.libs.ws.ning.NingWSRequest.post(NingWSRequest.java:322) ~[com.typesafe.play-play-java-ws_2.10-2.4.8.jar:2.4.8]
	at dao.SearchDAO.elasticSearchDatasetByKeyword(SearchDAO.java:410) ~[wherehows-frontend.jar:na]
	at controllers.api.v1.Search.searchByKeyword(Search.java:241) ~[wherehows-frontend.jar:na]
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$83$$anonfun$apply$83.apply(Routes.scala:2886) ~[wherehows-frontend.jar:na]
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$83$$anonfun$apply$83.apply(Routes.scala:2886) ~[wherehows-frontend.jar:na]
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.http.DefaultHttpRequestHandler$1.call(DefaultHttpRequestHandler.java:20) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70) [com.typesafe.play-play-iteratees_2.10-2.4.8.jar:2.4.8]
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang-scala-library-2.10.5.jar:na]
	at play.core.j.JavaAction.apply(JavaAction.scala:94) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at scala.Option.map(Option.scala:145) ~[org.scala-lang-scala-library-2.10.5.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[com.typesafe.play-play_2.10-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[com.typesafe.play-play-iteratees_2.10-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524) ~[com.typesafe.play-play-iteratees_2.10-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[com.typesafe.play-play-iteratees_2.10-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560) ~[com.typesafe.play-play-iteratees_2.10-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536) ~[com.typesafe.play-play-iteratees_2.10-2.4.8.jar:2.4.8]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536) ~[com.typesafe.play-play-iteratees_2.10-2.4.8.jar:2.4.8]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang-scala-library-2.10.5.jar:na]
	... 6 common frames omitted

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
