### ISSUE TITLE
Unable to see the Azkaban data in UI

### ISSUE THREAD

**Issue by jimmy-src** [linkedin/WhereHows#1441]
WhereHows version is v1.0.0

AZKABAN_EXECUTION_METADATA_ETL log 

no error,but UI no data

```
2018-10-11 17:33:33 INFO  m.e.s.a.AzkabanExecEtl:178 - PySystem path: ['/alidata4/wherehows/WhereHows-1.0.0/wherehows-backend/build/stage/wherehows-backend/lib/Lib', '/alidata4/wherehows/WhereHows-1.0.0/wherehows-backend/build/stage/wherehows-backend/lib/org.python-jython-standalone-2.7.0.jar/Lib', '__classpath__', '__pyclasspath__/', '/alidata4/wherehows/WhereHows-1.0.0/wherehows-backend/build/stage/wherehows-backend/lib/wherehows-etl-wherehows-etl.jar/jython']
2018-10-11 17:33:33 INFO  m.e.s.a.AzkabanExecEtl:37 - In AzkabanExecEtl java launch extract jython scripts
2018-10-11 17:33:35 INFO  jython script : AzkabanExtract:-2 - Begin Azkaban Extract
2018-10-11 17:33:35 INFO  jython script : AzkabanExtract:-2 - collect flow&jobs
2018-10-11 17:33:36 INFO  jython script : AzkabanExtract:-2 - collect owner&permissions
2018-10-11 17:33:36 INFO  jython script : AzkabanExtract:-2 - collect flow schedule
2018-10-11 17:33:36 INFO  jython script : AzkabanExtract:-2 - collect flow&job executions
2018-10-11 17:33:36 INFO  m.e.s.a.AzkabanExecEtl:46 - In AzkabanExecEtl java launch transform jython scripts
2018-10-11 17:33:37 INFO  m.e.s.a.AzkabanExecEtl:55 - In AzkabanExecEtl java launch load jython scripts
2018-10-11 17:33:37 INFO  m.e.s.a.AzkabanExecEtl:59 - In AzkabanExecEtl java load jython scripts finished
2018-10-11 17:33:37 INFO  Job Launcher:98 - whEtlExecId=139 finished.

```

AZKABAN_LINEAGE_METADATA_ETL log
error

```
2018-10-11 17:23:34 INFO  m.e.l.AzJobChecker:102 - Get the jobs from time : 1539244414492 to time : 1539249814492
2018-10-11 17:23:34 INFO  m.e.l.AzJobChecker:108 - Get recent flow sql : select exec_id, flow_id, status, submit_user, flow_data from execution_flows where end_time > 1539244414492 and end_time < 1539249814492
2018-10-11 17:23:35 INFO  m.e.l.AzLineageExtractorMaster:81 - Total number of azkaban jobs : 347
2018-10-11 17:23:35 ERROR Job Launcher:91 - java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460)
	at java.util.Properties.setProperty(Properties.java:166)
	at java.lang.System.setProperty(System.java:796)
	at metadata.etl.lineage.HadoopJobHistoryNodeExtractor.<init>(HadoopJobHistoryNodeExtractor.java:71)
	at metadata.etl.lineage.AzLineageExtractorMaster.run(AzLineageExtractorMaster.java:91)
	at metadata.etl.lineage.AzLineageExtractorMaster.run(AzLineageExtractorMaster.java:65)
	at metadata.etl.lineage.AzLineageMetadataEtl.extract(AzLineageMetadataEtl.java:88)
	at metadata.etl.EtlJob.run(EtlJob.java:179)
	at metadata.etl.Launcher.main(Launcher.java:86)

```

and the WHZ_ETL_TEMP_DIR has the Azkaban metedata

```
[hdfs@master1 howstmp]$ ls -l AZKABAN/14/
total 288
-rw-rw-r-- 1 hdfs hdfs 127553 Oct 11 17:33 dag.csv
-rw-rw-r-- 1 hdfs hdfs   5213 Oct 11 17:33 flow.csv
-rw-rw-r-- 1 hdfs hdfs   2560 Oct 11 17:33 flow_exec.csv
-rw-rw-r-- 1 hdfs hdfs  84299 Oct 11 17:33 job.csv
-rw-rw-r-- 1 hdfs hdfs  48989 Oct 11 17:33 job_exec.csv
-rw-rw-r-- 1 hdfs hdfs  10797 Oct 11 17:33 owner.csv
-rw-rw-r-- 1 hdfs hdfs   3569 Oct 11 17:33 schedule.csv
```

why? And how to resolve this? Thanks

**Comment by jimmy-src** [comment]
INSERT INTO cfg_application (app_id, app_code, description, parent_app_id, app_status) 
VALUES (14, "14", "azkaban task", 14, "1");

app_id is the table flow app_id
