### ISSUE TITLE
Can't build wherehows during wherehows-web:emberBuild

### ISSUE THREAD

**Issue by jkl0898** [linkedin/WhereHows#1483]
> Task :wherehows-web:emberBuild

Running without permission to symlink will degrade build performance.
See http://ember-cli.com/user-guide/#windows for details.

bootstrap-sassy config: some JS loaded [dropdown,collapse,tab], glyphicons enabled
cleaning up...
Build failed.
The Broccoli Plugin: [broccoli-persistent-filter:CleanCSSFilter] failed with:
Error: File to read not found or unreadable: D:/gitproject/WhereHows/wherehows-web/tmp/eyeglass_compiler-input_base_path-RaUaAD7q.tmp/D:/gitproject/WhereHows/wherehows-web/tmp/eyeglass_compiler-input_base_path-RaUaAD7q.tmp/app/styles/app.scss
    at undefined:undefined:undefined
    at options.error (D:\gitproject\WhereHows\wherehows-web\node_modules\node-sass\lib\index.js:291:26)

The broccoli plugin was instantiated at:
    at CleanCSSFilter.Plugin (D:\gitproject\WhereHows\wherehows-web\node_modules\broccoli-plugin\index.js:7:31)
    at CleanCSSFilter.Filter [as constructor] (D:\gitproject\WhereHows\wherehows-web\node_modules\broccoli-persistent-filter\index.js:64:10)
    at new CleanCSSFilter (D:\gitproject\WhereHows\wherehows-web\node_modules\broccoli-clean-css\index.js:17:10)
    at CleanCSSFilter (D:\gitproject\WhereHows\wherehows-web\node_modules\broccoli-clean-css\index.js:12:12)
    at module.exports.preprocessMinifyCss (D:\gitproject\WhereHows\wherehows-web\node_modules\ember-cli-preprocess-registry\preprocessors.js:112:12)
    at EmberApp.styles (D:\gitproject\WhereHows\wherehows-web\node_modules\ember-cli\lib\broccoli\ember-app.js:1466:30)
    at EmberApp.toArray (D:\gitproject\WhereHows\wherehows-web\node_modules\ember-cli\lib\broccoli\ember-app.js:1786:12)
    at EmberApp.toTree (D:\gitproject\WhereHows\wherehows-web\node_modules\ember-cli\lib\broccoli\ember-app.js:1809:32)
    at module.exports (D:\gitproject\WhereHows\wherehows-web\ember-cli-build.js:141:14)
    at Builder.setupBroccoliBuilder (D:\gitproject\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\builder.js:56:19)
    at new Builder (D:\gitproject\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\builder.js:30:10)
    at BuildTask.run (D:\gitproject\WhereHows\wherehows-web\node_modules\ember-cli\lib\tasks\build.js:15:19)
    at Promise.resolve.then (D:\gitproject\WhereHows\wherehows-web\node_modules\ember-cli\lib\models\command.js:243:46)
    at tryCatch (D:\gitproject\WhereHows\wherehows-web\node_modules\rsvp\dist\rsvp.js:525:12)
    at invokeCallback (D:\gitproject\WhereHows\wherehows-web\node_modules\rsvp\dist\rsvp.js:538:13)
    at D:\gitproject\WhereHows\wherehows-web\node_modules\rsvp\dist\rsvp.js:606:14
    at flush (D:\gitproject\WhereHows\wherehows-web\node_modules\rsvp\dist\rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wherehows-web:emberBuild'.
> Process 'command 'D:\gitproject\WhereHows\wherehows-web\build\nodejs\node-v8.9.1-win-x86\node.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 16m 32s
53 actionable tasks: 45 executed, 8 up-to-date

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
