### ISSUE TITLE
Bootstraping data not loading data

### ISSUE THREAD

**Issue by bartonneil** [linkedin/WhereHows#1512]
Have latest docker components up and running.  

When i attempt to bootstrap the sample data from the quickstart, I get error;

python mce_cli.py produce -d bootstrap_mce.dat

produces following output, followed by a large JSON document;

Producing MetadataChangeEvent records to topic MetadataChangeEvent. ^c to exit.
Traceback (most recent call last):
  File "mce_cli.py", line 107, in <module>
    main(parser.parse_args())
  File "mce_cli.py", line 89, in main
    produce(conf, args.data_file)
  File "mce_cli.py", line 33, in produce
    producer.produce(topic=topic, value=content)
  File "/Users/neil/opt/anaconda3/envs/aw_sand/lib/python2.7/site-packages/confluent_kafka/avro/__init__.py", line 80, in produce
    value = self._serializer.encode_record_with_schema(topic, value_schema, value)
  File "/Users/neil/opt/anaconda3/envs/aw_sand/lib/python2.7/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 115, in encode_record_with_schema
    return self.encode_record_with_schema_id(schema_id, record, is_key=is_key)
  File "/Users/neil/opt/anaconda3/envs/aw_sand/lib/python2.7/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 149, in encode_record_with_schema_id
    writer(record, outf)
  File "/Users/neil/opt/anaconda3/envs/aw_sand/lib/python2.7/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 86, in <lambda>
    return lambda record, fp: writer.write(record, avro.io.BinaryEncoder(fp))
  File "/Users/neil/opt/anaconda3/envs/aw_sand/lib/python2.7/site-packages/avro/io.py", line 1042, in write
    raise AvroTypeException(self.writers_schema, datum)
avro.io.AvroTypeException: The datum {'auditHeader': None, 'proposedSnapshot': ('com.linkedin.pegasus2avro.metadata.snapshot.CorpUserSnapshot', {'urn': 'urn:li:corpuser:datahub', 'aspects': [{'active': True, 'fullName': 'Data Hub', 'displayName': 'Data Hub', 'email': 'datahub@linkedin.com'}, {}]}), 'proposedDelta': None} is not an example of the schema 

Any help would be appreciated.

**Comment by RealChrisL** [comment]
@bartonneil 
Thanks for reaching out to Data Hub.

Regarding your datum writer issue, it might be caused by the mismatch of the ingested data and the Avro schema.

Could you please shut down the dockers and run the `docker-compose down` to clean up the caches in the Kafka schema registry.

Following the step,  make sure you pull the latest version (which you may have already done!), reinitializing the dockers and ingestion pipeline to see whether the issue persists.  

Chris

**Comment by bartonneil** [comment]
Thanks Chris,

I shutdown and restarted Docker a few times - no success..

I am running this on my mac (Catalina - 10.15) and found that the "sudo pip install --user -r requirements.txt" listed in the quickstart ended up creating a .local directory beneath my home directory, for the confluent_kafka requirements.  The **sudo** command cause that .local directory and related components to be owned by root, rather than my user account.

I deleted the .local and ran the pip install without sudo, so that .local was created under my user account and all seems to work now...

Not sure if anyone has seen this before.  However, seems to be functional and I will continue experimenting with the API access to feed in additional metadata.

Thanks for the response.
