### ISSUE TITLE
Build failed with an exception: :li-utils:generateDataTemplateFAILED

### ISSUE THREAD

**Issue by PriyaShaji** [linkedin/WhereHows#1515]
When I run "./gradlew :metadata-events:mxe-schemas:build", it gives me the following exception:
----------------------------------------------------------
> Task :li-utils:generateDataTemplate FAILED
Exception in thread "main" java.lang.NoClassDefFoundError: javax/annotation/Generated
        at com.linkedin.pegasus.generator.JavaCodeUtil.annotate(JavaCodeUtil.java:77)
        at com.linkedin.pegasus.generator.JavaDataTemplateGenerator.populateClassContent(JavaDataTemplateGenerator.java:1004)
        at com.linkedin.pegasus.generator.JavaDataTemplateGenerator.generate(JavaDataTemplateGenerator.java:252)
        at com.linkedin.pegasus.generator.PegasusDataTemplateGenerator.run(PegasusDataTemplateGenerator.java:133)
        at com.linkedin.pegasus.generator.PegasusDataTemplateGenerator.main(PegasusDataTemplateGenerator.java:105)
Caused by: java.lang.ClassNotFoundException: javax.annotation.Generated
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more
FAILURE: Build failed with an exception.
------------------------------------------------------------
Not able to figure out the error.

**Comment by keremsahin1** [comment]
@PriyaShaji Can you please tell me which java version you are using? `java -version`
I didn't find any issue with 2 different java versions as below:

```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```
```
openjdk 11.0.3 2019-04-16 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.3+7-LTS, mixed mode, sharing)
```

**Comment by PriyaShaji** [comment]
ok, it's my work system and it has java version 13
So, I suppose we degrade the java version?

**Comment by keremsahin1** [comment]
Thanks for quick reply. I take my above comment back. I was able to replicate your issue with Java 11. I guess @Generated annotation has been removed after Java 8 and that's why we are seeing this. So, we need to stick with Java 8 at this point.

**Comment by PriyaShaji** [comment]
ok, I will execute with Java 8 and update the issue. Thank you for your help.
