### ISSUE TITLE
zxJDBC.DatabaseError: driver ["com.mysql.jdbc.Driver"] not found

### ISSUE THREAD

**Issue by dmoore247** [linkedin/WhereHows#190]
I'm receiving driver not found error from Hive Jython script when running Hive metadata ETL. 

I'm guessing it's not dynamically loading the driver based on my afternoon's worth of research. MySQL jar file is in lib directory.

I'm running with a very recent fork.  Any help appreciated. Detailed log file & properties file attached.
Thank you!

> 2016-07-30 18:13:48 INFO  HiveMetadataEtl:39 - In Hive metadata ETL, launch extract jython scripts
2016-07-30 18:13:49 ERROR Job Launcher:80 - Traceback (most recent call last):
  File "<iostream>", line 302, in <module>
zxJDBC.DatabaseError: driver ["com.mysql.jdbc.Driver"] not found

        at org.python.core.PyException.doRaise(PyException.java:198)
        at org.python.core.Py.makeException(Py.java:1337)
        at org.python.core.Py.makeException(Py.java:1341)
        at com.ziclix.python.sql.zxJDBC.makeException(zxJDBC.java:329)
        at com.ziclix.python.sql.connect.Connect.__call__(Connect.java:79)
        at org.python.core.PyObject.__call__(PyObject.java:515)
        at org.python.core.PyObject.__call__(PyObject.java:521)
        at org.python.pycode._pyx0.f$0(<iostream>:308)
        at org.python.pycode._pyx0.call_function(<iostream>)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyCode.call(PyCode.java:18)
        at org.python.core.Py.runCode(Py.java:1386)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:291)
        at metadata.etl.dataset.hive.HiveMetadataEtl.extract(HiveMetadataEtl.java:42)
        at metadata.etl.EtlJob.run(EtlJob.java:181)
        at metadata.etl.Launcher.main(Launcher.java:75)

[bug-driver-not-found.txt](https://github.com/linkedin/WhereHows/files/392130/bug-driver-not-found.txt)
[hive-test.properties.txt](https://github.com/linkedin/WhereHows/files/392131/hive-test.properties.txt)
[go-hive.sh.txt](https://github.com/linkedin/WhereHows/files/392133/go-hive.sh.txt)

**Comment by dmoore247** [comment]
Any thoughts? The driver is in the CLASSPATH, I did find some posts about older versions of Jython not loading dynamic libraries, not sure that is applicable here. Thanks for your help.

**Comment by ericsun2** [comment]
We put jython-standalone-2.7.0 and mysql jdbc in the directory of [metadata-etl/extralibs], then after gradlew dist, both jar files will be available in "backend-service-1.0-SNAPSHOT/lib" directory.

https://github.com/linkedin/WhereHows/tree/master/metadata-etl/extralibs

**Comment by dmoore247** [comment]
Both of those jar files were in the classpath but I'll give this deployment procedure a shot.

**Comment by dmoore247** [comment]
Ok some very good success!
I have the Hive ETL running under the context of the backend-service. 

My initial attempts were under the stand alone (testing framework?) metadata-etl-1.0/bin/metadata-etl which are still failing. Both of those jars are in the class path and in the lib dir.

I'll post a guide or a README documenting how to do initial configuration for the backend service.
Thanks

**Comment by PettterPan** [comment]
@dmoore247  how can I get your guide ?
