### ISSUE TITLE
java.lang.AbstractMethodError: akka.event.slf4j.Slf4jLogger.aroundReceive  with backend server

### ISSUE THREAD

**Issue by superwood** [linkedin/WhereHows#207]
java.lang.AbstractMethodError: akka.event.slf4j.Slf4jLogger.aroundReceive  with backend server

version：1.0-SNAPSHOT

[ERROR] [08/24/2016 16:12:36.543] [WhereHowsETLService-akka.actor.default-dispatcher-4] [ActorSystem(WhereHowsETLService)] Uncaught error from thread [WhereHowsETLService-akka.actor.default-dispatcher-4] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.AbstractMethodError: akka.event.slf4j.Slf4jLogger.aroundReceive(Lscala/PartialFunction;Ljava/lang/Object;)V
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Uncaught error from thread [WhereHowsETLService-akka.actor.default-dispatcher-4] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[WhereHowsETLService]
java.lang.AbstractMethodError: akka.event.slf4j.Slf4jLogger.aroundReceive(Lscala/PartialFunction;Ljava/lang/Object;)V
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)

**Comment by ericsun2** [comment]
Hi @superwood, is it possible for you to attach/link the full stack trace? We are going to investigate.

**Comment by superwood** [comment]
The problem was fixed ， THX
