### ISSUE TITLE
org.gradle.api.internal.MissingMethodException

### ISSUE THREAD

**Issue by ecinamon** [linkedin/WhereHows#217]
Hi,

I am getting this while running gradle build:

Caused by: org.gradle.api.internal.MissingMethodException: Could not find method module() for arguments [org.slf4j:slf4j-log4j12] on org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultResolutionStrategy_Decorated@7a1a3468.
        at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:68)
        at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:56)
        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:175)
        at org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultResolutionStrategy_Decorated.invokeMethod(Unknown Source)
        at build_a37ns0gqj6tuhjeqoghvih0lr$_run_closure2_closure16_closure17.doCall(/home/ec2-user/WhereHows/backend-service/build.gradle:43)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)

Hope you can help me, thanks.

**Comment by ericsun2** [comment]
Hi @ecinamon, can you try to use `cd backend-service; ../gradlew build`?
Wondering if this has something to do with the gradle version.

**Comment by PettterPan** [comment]
Hi , I alse came across this problem . Can u give me some advice for this problem by details @ericsun2 . Thx

**Comment by ericsun2** [comment]
@ecinamon and @PettterPan did you try to use gradlew script to launch the build process?

**Comment by PettterPan** [comment]
@ericsun2  yeh~ it works ，thanks
