### ISSUE TITLE
Configuration error: Configuration error[database.conf: 5: Could not resolve substitution to a value: 

### ISSUE THREAD

**Issue by kevinbai0718** [linkedin/WhereHows#249]
Hi,

I'm going back to the **WhereHows** root directory and start the metadata ETL and API service: 
`cd backend-service ; $PLAY_HOME/play run`

then，throw an error：

SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Oops, cannot start the server.
Configuration error: Configuration error[database.conf: 5: Could not resolve substitution to a value: ${WHZ_DB_PASSWORD}]
        at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:92)
        at play.api.Configuration$.load(Configuration.scala:58)
        at play.api.WithDefaultConfiguration$$anonfun$initialConfiguration$1.apply(Application.scala:72)
        at play.api.WithDefaultConfiguration$$anonfun$initialConfiguration$1.apply(Application.scala:72)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
        at play.api.WithDefaultConfiguration$class.initialConfiguration(Application.scala:71)
        at play.api.DefaultApplication.initialConfiguration$lzycompute(Application.scala:399)
        at play.api.DefaultApplication.initialConfiguration(Application.scala:399)
        at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$globalClass(Application.scala:22)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalClass$lzycompute(Application.scala:399)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalClass(Application.scala:399)
        at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$javaGlobal(Application.scala:28)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$javaGlobal$lzycompute(Application.scala:399)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$javaGlobal(Application.scala:399)
        at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:50)
        at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:49)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:18)
        at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$globalInstance(Application.scala:48)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalInstance$lzycompute(Application.scala:399)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalInstance(Application.scala:399)
        at play.api.WithDefaultGlobal$class.global(Application.scala:64)
        at play.api.DefaultApplication.global(Application.scala:399)
        at play.api.WithDefaultConfiguration$class.play$api$WithDefaultConfiguration$$fullConfiguration(Application.scala:78)
        at play.api.DefaultApplication.play$api$WithDefaultConfiguration$$fullConfiguration$lzycompute(Application.scala:399)
        at play.api.DefaultApplication.play$api$WithDefaultConfiguration$$fullConfiguration(Application.scala:399)
        at play.api.WithDefaultConfiguration$class.configuration(Application.scala:80)
        at play.api.DefaultApplication.configuration(Application.scala:399)
        at play.api.Application$class.$init$(Application.scala:272)
        at play.api.DefaultApplication.<init>(Application.scala:399)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:50)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:316)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:311)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:311)
        at play.core.server.NettyServer.main(NettyServer.scala)

Please give me some help.Thanks！

**Comment by ericsun2** [comment]
@kevinbai0718 please see the "Run" section of https://github.com/linkedin/WhereHows/blob/master/backend-service/README.md

You may need to provide the connection info via env variables or you many need to code them in database.conf

**Comment by kevinbai0718** [comment]
@ericsun2 Thanks a lot,The problem has been solved.
