### ISSUE TITLE
Cannot find metadata.etl.launcher

### ISSUE THREAD

**Issue by msharma011** [linkedin/WhereHows#338]
Error: Could not find or load main class metadata.etl.Launcher

java.lang.Exception: Process + 3466 failed
	at actors.EtlJobActor.onReceive(EtlJobActor.java:79)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
java.lang.Exception: Process + 3465 failed
	at actors.EtlJobActor.onReceive(EtlJobActor.java:79)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] - application - ETL job (jobType:HIVE_DATASET_METADATA_ETL refIdType:DB refId: 61 whEtlJobId:  21 whEtlExecId:  179) got a problem
[error] - application - ETL job (jobType:ORACLE_DATASET_METADATA_ETL refIdType:DB refId: 62 whEtlJobId:  22 whEtlExecId:  180) got a problem

**Comment by thomas-young-2013** [comment]
run it by using "runBackend -Dhttp.port=port_number" under the backend-service dir , instead of "activator run -Dhttp.port=port_number"

**Comment by yanshuining** [comment]
get the same error as "Error: Could not find or load main class metadata.etl.Launcher" when running command as "$ACTIVATOR_HOME/bin/activator run -Dhttp.port=<port number>"
I tried to run the command as "$ACTIVATOR_HOME/bin/activator runBackend -Dhttp.port=<port number>", but it says runBackend not a valid command.

**Comment by alyiwang** [comment]
At the backend-service folder, after properly set the parameters in conf/application.conf then `../gradlew clean build dist`, the command `./runBackend` will start the server and launch the jobs as specified.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
