### ISSUE TITLE
global name 'schema' is not defined

### ISSUE THREAD

**Issue by kiranalda** [linkedin/WhereHows#457]
I am getting this error 2017-04-26 12:15:53 ERROR Job Launcher:86 - Traceback (most recent call last):
  File "<iostream>", line 403, in <module>
  File "<iostream>", line 360, in run
NameError: global name 'schema' is not defined.

It seems schema variable was never declared in OracleExtract.py.

You can see the below that schema param is not mentioned in the param list.

 def format_table_metadata(self, rows):
    '''
    add table info from rows into schema
    :param rows: input. each row is a database with all it's tables
    :param schema: {schema : _, type : _, tables : ['name' : _, ... 'original_name' : _] }
    :return:
    '''

Line which is giving error in  OracleExtract.py is : - 

 _# collect sample data
      for onedatabase in schema:
        database_name = onedatabase['database_']

**Comment by chenbinggui** [comment]
I got the same error too，so I ignore the parameter ：

**Comment by chenbinggui** [comment]
e.run(None, None,
          args[Constant.ORA_SCHEMA_OUTPUT_KEY],
          args[Constant.ORA_FIELD_OUTPUT_KEY],
          args[Constant.ORA_SAMPLE_OUTPUT_KEY])
  ##        sample=collect_sample)

**Comment by alyiwang** [comment]
@kiranalda @chenbinggui , thanks for raising the issue. The data sampling part of Oracle Extract is not properly tested yet. We currently disabled it in our production, but will invest time into making it work.

**Comment by nikhiltanwar** [comment]
Is there any movement on this?

I am also facing the same:

```
2017-06-12 04:56:21 ERROR Job Launcher:83 - Traceback (most recent call last):
  File "<iostream>", line 403, in <module>
  File "<iostream>", line 360, in run
NameError: global name 'schema' is not defined

        at org.python.core.Py.NameError(Py.java:284)
        at org.python.core.PyFrame.getglobal(PyFrame.java:265)
        at org.python.pycode._pyx0.run$14(<iostream>:377)
        at org.python.pycode._pyx0.call_function(<iostream>)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
        at org.python.core.PyFunction.__call__(PyFunction.java:482)
        at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
        at org.python.core.PyMethod.__call__(PyMethod.java:228)
        at org.python.pycode._pyx0.f$0(<iostream>:410)
        at org.python.pycode._pyx0.call_function(<iostream>)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyCode.call(PyCode.java:18)
        at org.python.core.Py.runCode(Py.java:1386)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:291)
        at metadata.etl.dataset.oracle.OracleMetadataEtl.extract(OracleMetadataEtl.java:39)
        at metadata.etl.EtlJob.run(EtlJob.java:179)
        at metadata.etl.Launcher.main(Launcher.java:78)
```

Any workarounds other than editing code?

**Comment by nikhiltanwar** [comment]
Ok i debugged this issue and the problem is OracleExtract.py expects variable to be Boolean but it is a string so it always gets passed as true. Perhaps a str_to_bool function will help. 

```
def str_to_bool(s):
    if s == 'True':
         return True
    elif s == 'False':
         return False
    else:
         raise ValueError
```

**Comment by kiranalda** [comment]
Thanks @alyiwang ...but since extracting the sample record was one of our requirement, I was able to write code for this.And its working fine.
