### ISSUE TITLE
My active job did not run any once

### ISSUE THREAD

**Issue by rickywu** [linkedin/WhereHows#524]
Get /etls
```
{
  "return_code": 200,
  "etl_jobs": [
    {
      "wh_etl_job_id": 1,
      "wh_etl_job_name": "TERADATA_DATASET_METADATA_ETL",
      "wh_etl_type": "DATASET",
      "cron_expr": "0 10 * * * ?",
      "ref_id": 10001,
      "ref_id_type": "DB",
      "timeout": null,
      "next_run": 1495483800,
      "comments": "Teradata metadata etl",
      "cmd_param": "",
      "is_active": "Y"
    }
  ]
}
```

Get /cfg/dbs
```
{
  "return_code": 200,
  "databases": [
    {
      "db_id": 10001,
      "db_code": "ETL_UAT",
      "primary_dataset_type": "0",
      "description": "TERADATA ETL_UAT",
      "is_logical": "N",
      "deployment_tier": "prod",
      "data_center": "*",
      "associated_dc_num": 1,
      "cluster": "*",
      "cluster_size": 22,
      "extra_deployment_tag1": null,
      "extra_deployment_tag2": null,
      "extra_deployment_tag3": null,
      "replication_role": "MASTER",
      "jdbc_url": "jdbc:teradata://10.16.0.77/DBS_PORT=1025,database=ETL_UAT,USER=etl_uat,PASSWORD=etl_uat123,tmode=TERA,charset=ASCII,CLIENT_CHARSET=cp936,LOB_SUPPORT=ON",
      "uri": "jdbc:teradata://10.16.0.77/DBS_PORT=1025,database=ETL_UAT,USER=etl_uat,PASSWORD=etl_uat123,tmode=TERA,charset=ASCII,CLIENT_CHARSET=cp936,LOB_SUPPORT=ON",
      "short_connection_string": "ETL_UAT",
      "last_modified": 1495559007000
    }
  ]
}
```

After the next_run time, there is no any log file created

**Comment by xiatian051** [comment]
the same happend to me，can anyone help

**Comment by rickywu** [comment]
Can anyone help?

**Comment by mars-lan** [comment]
Can you check if the corresponding etl job id (1) is whitelisted in your application.conf (https://github.com/linkedin/WhereHows/blob/master/backend-service/conf/application.conf#L59)?

**Comment by rickywu** [comment]
I've tried add into whitelist, but got this error, and still no any log file

```
[ERROR] [06/15/2017 10:00:15.942] [WhereHowsETLService-akka.actor.default-dispatcher-18] [akka://WhereHowsETLService/user/EtlJobActor] null
java.lang.NullPointerException
        at actors.EtlJobActor.onReceive(EtlJobActor.java:115)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by mars-lan** [comment]
Are you building from master's head? The line number doesn't seem to point to a meaningful place. Could you also include the full logs? Thanks.

**Comment by rickywu** [comment]
I've tried build again in a virtual machine and still the same problem
The last build step is use gradlew build dist to generate two projects' distribution and run scripts under bin/

```
2017-06-22 22:11:27 INFO  application:55 - running job: job id :1
2017-06-22 22:11:27 INFO  application:74 - Current running jobs : 
2017-06-22 22:11:27 INFO  application:81 - Send message : (jobType:TERADATA_DATASET_METADATA_ETL refIdType:DB refId:10001 whEtlJobId:   1 whEtlExecId:    3)
java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:459)
        at models.daos.EtlJobPropertyDao.getJobProperties(EtlJobPropertyDao.java:134)
        at actors.EtlJobActor.onReceive(EtlJobActor.java:45)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2017-06-22 22:11:27 ERROR application:114 - ETL job (jobType:TERADATA_DATASET_METADATA_ETL refIdType:DB refId:10001 whEtlJobId:   1 whEtlExecId:    3) got a problem
[ERROR] [06/22/2017 22:11:27.648] [WhereHowsETLService-akka.actor.default-dispatcher-32] [akka://WhereHowsETLService/user/EtlJobActor] null
java.lang.NullPointerException
        at actors.EtlJobActor.onReceive(EtlJobActor.java:115)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2017-06-22 22:21:27 INFO  application:49 - total 0 jobs due, white list : [1, 2, 3, 4, 5, 6, 7, 8, 9]
```

**Comment by ankurgadgilwar** [comment]
I am trying to run the HIVE_METADAT_ETL job from the 1.0.0 tag and it is only failing at the similar point mentioned above. The job file has no option to store the logs for the job, so there are no logs being created anywhere.

**Comment by ankurgadgilwar** [comment]
java.lang.Exception: Process + 730953 failed
        at actors.EtlJobActor.onReceive(EtlJobActor.java:123)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-06-07 02:47:13 ERROR application:138 - ETL job (jobName:HIVE_METADATA_ETL, whEtlExecId:4) got a problem

**Comment by ankurgadgilwar** [comment]
The error is being thrown from the `EtlJobActor.java` file, I dont understand what exactly it is that isn't working.

**Comment by rickywu** [comment]
I used docker container run correctly, maybe it's an alternative way.

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
