### ISSUE TITLE
ERROR while running HIVE_DATASET_METADATA_ETL job

### ISSUE THREAD

**Issue by nikhiltanwar** [linkedin/WhereHows#534]
Hi,

I am running hive metadata ETL job, all configuration seems correct on my setup side but in the end i see a python error:

Traceback of job from /var/tmp/wherehows/HIVE_DATASET_METADATA_ETL.log :

```
2017-05-26 02:14:01 INFO  m.e.d.h.HiveMetadataEtl:178 - PySystem path: ['/opt/wherehows/WhereHows/backend-service/target/universal/stage/lib/Lib', '/opt/wherehows/WhereHows/backend-service/target/universal/stage/lib/jython-standalone-2.7.0.jar/Lib', '__classpath__', '__pyclasspath__/', '/opt/wherehows/WhereHows/backend-service/target/universal/stage/lib/metadata-etl.jar/jython']
2017-05-26 02:14:01 INFO  m.e.d.h.HiveMetadataEtl:39 - In Hive metadata ETL, launch extract jython scripts
2017-05-26 02:14:09 INFO  jython script : HiveExtract:-2 - SELECT `NAME` FROM DBS WHERE `NAME` IN ('''') OR NOT (`NAME` IN ('''') OR `NAME` LIKE 'u\_%')
2017-05-26 02:14:09 ERROR Job Launcher:83 - Traceback (most recent call last):
  File "<iostream>", line 504, in <module>
  File "<iostream>", line 314, in run
  File "/opt/wherehows/WhereHows/backend-service/target/universal/stage/lib/metadata-etl.jar/jython/SchemaUrlHelper.py", line 74, in __init__
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

        at org.python.core.Py.TypeError(Py.java:259)
        at org.python.core.PyObject._basic_add(PyObject.java:2141)
        at org.python.core.PyObject._add(PyObject.java:2119)
        at SchemaUrlHelper$py.__init__$2(/opt/wherehows/WhereHows/backend-service/target/universal/stage/lib/metadata-etl.jar/jython/SchemaUrlHelper.py:86)
        at SchemaUrlHelper$py.call_function(/opt/wherehows/WhereHows/backend-service/target/universal/stage/lib/metadata-etl.jar/jython/SchemaUrlHelper.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
        at org.python.core.PyFunction.__call__(PyFunction.java:482)
        at org.python.core.PyFunction.__call__(PyFunction.java:476)
        at org.python.core.PyInstance.__init__(PyInstance.java:124)
        at org.python.core.PyClass.__call__(PyClass.java:193)
        at org.python.core.PyObject.__call__(PyObject.java:515)
        at org.python.core.PyObject.__call__(PyObject.java:521)
        at org.python.pycode._pyx0.run$9(<iostream>:366)
        at org.python.pycode._pyx0.call_function(<iostream>)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
        at org.python.core.PyFunction.__call__(PyFunction.java:482)
        at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
        at org.python.core.PyMethod.__call__(PyMethod.java:228)
        at org.python.core.PyMethod.__call__(PyMethod.java:218)
        at org.python.pycode._pyx0.f$0(<iostream>:513)
        at org.python.pycode._pyx0.call_function(<iostream>)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyCode.call(PyCode.java:18)
        at org.python.core.Py.runCode(Py.java:1386)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:291)
        at metadata.etl.dataset.hive.HiveMetadataEtl.extract(HiveMetadataEtl.java:42)
        at metadata.etl.EtlJob.run(EtlJob.java:179)
        at metadata.etl.Launcher.main(Launcher.java:78)
```

**Comment by nikhiltanwar** [comment]
Solved by correcting path of keytab file. Source script looks for a starting '/' which was not there in path and else condition was getting executed in  SchemaUrlHelper.py
