### ISSUE TITLE
HDFS ETL job error ChannelSFTP.put is not working

### ISSUE THREAD

**Issue by nikhiltanwar** [linkedin/WhereHows#536]
Hi
I am trying to run HDFS ETL JOB is remote mode.  Currently the job fails. 

schemaFetch.jar is getting created but has size 0 bytes. 

Here is the job log:
```
2017-05-26 12:55:53 INFO  m.e.d.h.HdfsMetadataEtl:178 - PySystem path: ['/opt/wherehows/WhereHows/backend-service/target/universal/stage/lib/Lib', '/opt/wherehows/WhereHows/backend-service/target/universal/stage/lib/jython-standalone-2.7.0.jar/Lib', '__classpath__', '__pyclasspath__/', '/opt/wherehows/WhereHows/backend-service/target/universal/stage/lib/metadata-etl.jar/jython']
2017-05-26 12:55:53 INFO  m.e.d.h.HdfsMetadataEtl:71 - Begin hdfs metadata extract! - 27
2017-05-26 12:55:53 INFO  m.e.d.h.HdfsMetadataEtl:150 - Remote mode!
2017-05-26 12:55:54 ERROR m.e.d.h.HdfsMetadataEtl:235 - hdfs metadata collection error!
2017-05-26 12:55:54 ERROR m.e.d.h.HdfsMetadataEtl:239 - 4: java.lang.NullPointerException
        at com.jcraft.jsch.ChannelSftp._put(ChannelSftp.java:697)
        at com.jcraft.jsch.ChannelSftp.put(ChannelSftp.java:540)
        at com.jcraft.jsch.ChannelSftp.put(ChannelSftp.java:495)
        at metadata.etl.dataset.hdfs.HdfsMetadataEtl.extractRemote(HdfsMetadataEtl.java:177)
        at metadata.etl.dataset.hdfs.HdfsMetadataEtl.extract(HdfsMetadataEtl.java:74)
        at metadata.etl.EtlJob.run(EtlJob.java:179)
        at metadata.etl.Launcher.main(Launcher.java:78)
Caused by: java.lang.NullPointerException
        at com.jcraft.jsch.ChannelSftp._put(ChannelSftp.java:636)
        ... 6 more

2017-05-26 12:55:54 ERROR Job Launcher:83 - 4: java.lang.NullPointerException
        at com.jcraft.jsch.ChannelSftp._put(ChannelSftp.java:697)
        at com.jcraft.jsch.ChannelSftp.put(ChannelSftp.java:540)
        at com.jcraft.jsch.ChannelSftp.put(ChannelSftp.java:495)
        at metadata.etl.dataset.hdfs.HdfsMetadataEtl.extractRemote(HdfsMetadataEtl.java:177)
        at metadata.etl.dataset.hdfs.HdfsMetadataEtl.extract(HdfsMetadataEtl.java:74)
        at metadata.etl.EtlJob.run(EtlJob.java:179)
        at metadata.etl.Launcher.main(Launcher.java:78)
Caused by: java.lang.NullPointerException
        at com.jcraft.jsch.ChannelSftp._put(ChannelSftp.java:636)
        ... 6 more
```

I suspect that  channelSFTP.put is not working. 

I am running this on RHEL 7.1. Is this because of some system security?

**Comment by nikhiltanwar** [comment]
I think some path is not set properly. Please can someone point out what path do i need to set explicitly?

**Comment by nikhiltanwar** [comment]
Build is not able to locate "jar/schemaFetch.jar" which is supposed to be copied to remote server. How to correct this?

**Comment by nikhiltanwar** [comment]
**Update**: I try with the local mode and everything works fine. Remote mode had some unidentified issue.

**Comment by thomas-young-2013** [comment]
I suceeded in remote mode, the file path in your configuration may have some problems or jsch's authorization!

**Comment by nikhiltanwar** [comment]
File path is correct. schemaFetch.jar gets created in remote server is expected directory with size 0 bytes. I am using RHEL 7.1 not sure why this happened.

**Comment by thomas-young-2013** [comment]
make sure config for hdfs is correct and schema fetch works correctly, you can run it in terminal shell with command to test it

**Comment by nikhiltanwar** [comment]
Here is the setting that i gave:

```
    "properties": {"hdfs.cluster": "Cluster 1",

                   "hdfs.remote.machine": "<IP>",

                   "hdfs.private_key_location": "/home/wherehows.admin/.ssh/id_rsa",

                   "hdfs.remote.jar": "/home/wherehows.admin/schemaFetch.jar",

                   "hdfs.remote.user": "wherehows.admin",

                   "hdfs.remote.raw_metadata": "/home/wherehows.admin/wherehows_tmp/hdfs/hdfs_remote_raw_metadata",

                   "hdfs.remote.sample":"/home/wherehows.admin/wherehows_tmp/hdfs/hdfs_remote_sample",


                   "hdfs.local.field_metadata":"/home/wherehows.admin/wherehows_tmp/hdfs/hdfs_field_meta",


                    "hdfs.local.metadata":"/home/wherehows.admin/wherehows_tmp/hdfs/hdfs_meta",


                    "hdfs.local.raw_metadata": 

                   "/home/wherehows.admin/wherehows_tmp/hdfs/hdfs_raw_meta",


                    "hdfs.local.sample":"/home/wherehows.admin/wherehows_tmp/hdfs/hdfs_sample", 


                   "hdfs.white_list":"/tmp,/user",


                   "hdfs.num_of_thread": "2",


                   "hdfs.file_path_regex_source_map": "[{\"/home/wherehows.admin/wherehows_tmp/hdfs/tracking.\":\"Kafka\"},{\"/home/wherehows.admin/wherehows_tmp/hdfs/retail.\":\"Teradata\"}]",


                   "hdfs.remote.mode":"false",
					

                   "hdfs.remote.keytab.location":"/home/wherehows.admin/wherehows.admin.keytab",


                   "hdfs.namenode.ipc.uri":"hdfs://IP:8020"

                  }
```
Yes, i tried the job manually and it works. Everything worked perfectly when i used local mode. In fact i used the same database just updated "hdfs.remote.mode"  and everything worked perfectly fine in local mode. I just had to build the app on name node and configure some ports. 
I would have dig more to why this was happening but got dead end after this error. 
I will retest this case once i am done playing with Local mode. I had great success so far with local mode.

**Comment by nikhiltanwar** [comment]
I even tried to manually scp the file schemaFetch.jar from wherehows server to name node and it worked. Not sure why ChannelSFTP.put did not work.

**Comment by thomas-young-2013** [comment]
tips from personal experimence: compile the source again (./gradlew clean build dist) then run the backend

**Comment by thomas-young-2013** [comment]
The properties needed to configure in remote mode: 
![image](https://cloud.githubusercontent.com/assets/11434893/26818679/33b4e5da-4ace-11e7-8dc5-a726cfa841c1.png)

**Comment by nikhiltanwar** [comment]
I had set all of those, even more. See above in my setting. Anyway this did not reappear and i am now moving to latest build hence this is obsolete now. I will close this.

**Comment by sagartoms** [comment]
@nikhiltanwar can you help me in running the hdfs etl job?

**Comment by nikhiltanwar** [comment]
@sagartoms Please use the parameters in this thread and try, it should work.  Also rest api documentation is very good. Please take reference from there.

**Comment by diaowenyang** [comment]
@thomas-young-2013 Which version do you choose ? Now I user v1.0.0 ,it add hdfs dataset to wherehows errer
2017-12-05 17:25:42 ERROR m.e.d.h.HdfsMetadataEtl:165 - *** Process  failed, status: 1
2017-12-05 17:25:42 ERROR m.e.d.h.HdfsMetadataEtl:166 - HDFS Metadata Extract Error:

2017-12-05 17:25:42 ERROR Job Launcher:91 - java.lang.Exception: Process + -1 failed
	at metadata.etl.dataset.hdfs.HdfsMetadataEtl.extractLocal(HdfsMetadataEtl.java:167)
	at metadata.etl.dataset.hdfs.HdfsMetadataEtl.extract(HdfsMetadataEtl.java:86)
	at metadata.etl.EtlJob.run(EtlJob.java:179)
	at metadata.etl.Launcher.main(Launcher.java:86)

Can you help to fix it ?

**Comment by kartik18** [comment]
@diaowenyang I'm this kind of issue for v1.0.0 as well. Both for my HDFS and Oozie job. Logs for Oozie
and HDFS are exactly same. Same stack trace followed by their job name. Any help on this ?

wherehows-backend_1        | 2018-08-24 18:35:42 ERROR application:121 - *** Process + 47 failed, status: 1
wherehows-backend_1        | 2018-08-24 18:35:42 ERROR application:122 - Error Details:
wherehows-backend_1        |
wherehows-backend_1        | 2018-08-24 18:35:42 ERROR application:138 - ETL job (jobName:OOZIE_EXECUTION_METADATA_ETL, whEtlExecId:73) got a problem
wherehows-backend_1        | java.lang.Exception: Process + 47 failed
wherehows-backend_1        |    at actors.EtlJobActor.onReceive(EtlJobActor.java:123)
wherehows-backend_1        |    at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
wherehows-backend_1        |    at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
wherehows-backend_1        |    at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
wherehows-backend_1        |    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
wherehows-backend_1        |    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
wherehows-backend_1        |    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
wherehows-backend_1        |    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
wherehows-backend_1        |    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
wherehows-backend_1        |    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
wherehows-backend_1        |    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
wherehows-backend_1        |    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
wherehows-backend_1        |    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
