### ISSUE TITLE
Hive Metadata ETL Error

### ISSUE THREAD

**Issue by HetongWang** [linkedin/WhereHows#615]
Hi, I got `Class path contains multiple SLF4J bindings` Error when ran a Hive ETL job. The logs are following:
```
2017-07-25 16:45:24 ERROR application:98 - Error Details:
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/WhereHows/target/backend/lib/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/WhereHows/target/backend/lib/ch.qos.logback.logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

java.lang.Exception: Process + 27834 failed
	at actors.EtlJobActor.onReceive(EtlJobActor.java:99)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2017-07-25 16:45:24 ERROR application:114 - ETL job (jobType:HIVE_DATASET_METADATA_ETL refIdType:DB refId:  0 whEtlJobId:   1 whEtlExecId:    7) got a problem
```

However after I deleted one binding from .jar file, The error still occurs but with no error details
```
2017-07-25 17:28:24 ERROR application:98 - Error Details:

java.lang.Exception: Process + 1733 failed
	at actors.EtlJobActor.onReceive(EtlJobActor.java:99)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2017-07-25 17:28:24 ERROR application:114 - ETL job (jobType:HIVE_DATASET_METADATA_ETL refIdType:DB refId:  0 whEtlJobId:   1 whEtlExecId:    8) got a problem
```
My WhereHows version is v0.2.1 and I did follow the step-by-step Instructions of setting up a new ETL job.

Much appreciated for your help

**Comment by HetongWang** [comment]
Here is output in `HIVE_DATASET_METADATA_ETL.log` file.
```
2017-07-27 13:22:11 INFO  m.e.d.h.HiveMetadataEtl:178 - PySystem path: ['/root/WhereHows/target/backend/lib/Lib', '/root/WhereHows/target/backend/lib/jython-standalone-2.7.0.jar/Lib', '__classpath__', '__pyclasspath__/', '/root/WhereHows/target/backend/lib/metadata-etl.jar/jython']
2017-07-27 13:22:11 INFO  m.e.d.h.HiveMetadataEtl:39 - In Hive metadata ETL, launch extract jython scripts
2017-07-27 13:22:22 INFO  jython script : HiveExtract:-2 - SELECT `NAME` FROM DBS WHERE `NAME` IN ('''') OR NOT (`NAME` IN ('''') OR `NAME` LIKE 'u\_%')
2017-07-27 13:22:22 ERROR Job Launcher:83 - Traceback (most recent call last):
  File "<iostream>", line 504, in <module>
KeyError: hive.hdfs_map_csv_file

	at org.python.core.Py.KeyError(Py.java:249)
	at org.python.core.PyObject.__getitem__(PyObject.java:738)
	at org.python.pycode._pyx0.f$0(<iostream>:513)
	at org.python.pycode._pyx0.call_function(<iostream>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:291)
	at metadata.etl.dataset.hive.HiveMetadataEtl.extract(HiveMetadataEtl.java:42)
	at metadata.etl.EtlJob.run(EtlJob.java:179)
	at metadata.etl.Launcher.main(Launcher.java:78)

```

**Comment by nikhiltanwar** [comment]
You have not set `hdfs_map_csv_file` parameter.

**Comment by HetongWang** [comment]
Fixed by adding following additional properties to wh_etl_job_property which are not mentioned in documentation.
```
|  8 | HIVE_DATASET_METADATA_ETL |      0 | DB          | hive.hdfs_map_csv_file     | /var/tmp/wherehows/hive_hdfs_map.csv       | N            | NULL     |
|  9 | HIVE_DATASET_METADATA_ETL |      0 | DB          | hdfs.namenode.ipc.uri      | hdfs://localhost:9000                   | N            | NULL     |
| 10 | HIVE_DATASET_METADATA_ETL |      0 | DB          | hive.dependency_csv_file   | /var/tmp/wherehows/hive_dependency.csv     | N            | NULL     |
| 11 | HIVE_DATASET_METADATA_ETL |      0 | DB          | hive.instance_csv_file     | /var/tmp/wherehows/hive_instance.csv       | N            | NULL     |

```
