### ISSUE TITLE
Cannot log into web client on quickstart VM

### ISSUE THREAD

**Issue by taylorterry3** [linkedin/WhereHows#64]
Thanks for open-sourcing this! I'm trying to get the quickstart examples running in the VM, but I'm having problems getting logged into the web client. I can get the frontend and backend running, but when I go to log in to the web client running on 9008 it spins for a while and then I get `Invalid username or password`. The users table in mysql has an entry for `wherehows` with a stored has that matches `sha1("wherehows")`, so I don't think it's actually an auth issue. The backend console shows the following:

```
[error] application - Could not get JDBC Connection; nested exception is java.sql.SQLException: Unable to open a test connection to the given database. JDBC url = jdbc:mysql://172.21.98.60/wherehows?charset=utf8&zeroDateTimeBehavior=convertToNull, username = wherehows.
```
I've run `/root/bin/enable-all-hadoop-service.sh` and tried starting the frontend before the backend and vice versa. This seems to be a pretty straightforward "I can't find mysql" error, but I'm kind of at a loss for how to fix it. Any help greatly appreciated!

Full trace from the frontend:
```
cloudera@quickstart wherehows]$ ./runfrontend 
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Play server process ID is 15205
[info] play - Application started (Prod)
[info] play - Listening for HTTP on /0.0.0.0:9008
[error] application - Authentication failed for user wherehows
[error] application - Could not get JDBC Connection; nested exception is java.sql.SQLException: Unable to open a test connection to the given database. JDBC url = jdbc:mysql://172.21.98.60/wherehows?charset=utf8&zeroDateTimeBehavior=convertToNull, username = wherehows. Terminating connection pool (set lazyInit to true if you expect to start your database after your app). Original Exception: ------
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1117)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:350)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2408)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:627)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:692)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:724)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:734)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:784)
	at org.springframework.jdbc.core.JdbcTemplate.queryForList(JdbcTemplate.java:889)
	at dao.UserDAO.authenticate(UserDAO.java:109)
	at security.AuthenticationManager.authenticateUser(AuthenticationManager.java:42)
	at controllers.Application.authenticate(Application.java:130)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$4$$anonfun$apply$4.apply(routes_routing.scala:341)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$4$$anonfun$apply$4.apply(routes_routing.scala:341)
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183)
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56)
	at play.GlobalSettings$1.call(GlobalSettings.java:64)
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91)
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90)
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:259)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 48 more
------
```

**Comment by jerrybai2009** [comment]
Hi,
When did you download the vm image?
It looks like the image is old.

From the log,
[error] application - Could not get JDBC Connection; nested exception is java.sql.SQLException: Unable to open a test connection to the given database. JDBC url = jdbc:mysql://172.21.98.60/wherehows?charset=utf8&zeroDateTimeBehavior=convertToNull, username = wherehows. Terminating connection pool (set lazyInit to true if you expect to start your database after your app). Original Exception: ------
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

It looks like the application is trying to connect to mysql db host on 172.21.98.60.
It should be connect to host localhost.

database.opensource.url = "jdbc:mysql://localhost/wherehows?charset=utf8&zeroDateTimeBehavior=convertToNull"

You can see it in file application.conf, under folder /home/cloudera/wherehows/wherehows-1.0-SNAPSHOT/conf/.

Thanks!

**Comment by hcove42** [comment]
Hi, 

I  downloaded the WM Saturday, and I also have the same problem where it hangs during the login and returns with an "Invalid user .." message. I checked the log and I can see it is referring to the same IP "172.21.98.60". 

Where do I change this so it refers to Localhost - I'm far from a Linux expert - so please be precise ;-)

Regards,
Hans Christian

**Comment by taylorterry3** [comment]
Thanks for the reply!  I downloaded it on Friday, and I have that exact line in the config file:

```
database.opensource.url = "jdbc:mysql://localhost/wherehows?charset=utf8&zeroDateTimeBehavior=convertToNull"
```
I did some grepping in the application folders for `172.21.98.60` and didn't find anything but logged errors.

Is there a hash of the VM image or some other way to check the version of the files?

**Comment by nbateshaus** [comment]
I am seeing this on the VM as well. I grabbed the image on Friday 3/4.
Mine is also trying to connect to MySQL on IP 172.21.98.60
Setting this in application.conf is ignored - even setting it to gibberish, e.g. database.opensource.url = "you:shall:not:connect" it attempts to connect to 172.21.98.60

**Comment by kevinrhaas** [comment]
I see the same behavior as others in the VM, downloaded Friday 3/4. I grepped around and looked for a config file with that IP, but none turned up. I did see that IP referred to the MySQL database for an Azkaban server, (not MySQL).

-----
2016-03-07 12:17:37,033 - [INFO] - from play in main 
Application started (Prod)

2016-03-07 12:17:37,170 - [INFO] - from play in main 
Listening for HTTP on /0.0.0.0:9008

2016-03-07 12:20:01,774 - [ERROR] - from application in play-akka.actor.default-dispatcher-2 
Authentication failed for user wherehows

2016-03-07 12:20:01,774 - [ERROR] - from application in play-akka.actor.default-dispatcher-2 
Could not get JDBC Connection; nested exception is java.sql.SQLException: Unable to open a test connection to the given database. JDBC url = jdbc:mysql://172.21.98.60/wherehows?charset=utf8&zeroDateTimeBehavior=convertToNull, username = wherehows. Terminating connection pool (set lazyInit to true if you expect to start your database after your app). Original Exception: ------
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

**Comment by SunZhaonan** [comment]
We tried on different machines didn't see this error... let me try use my own computer outside of internal network.

**Comment by jerrybai2009** [comment]
Can you try below steps to restart the front server?

1. get the font server process id
cat /home/cloudera/wherehows/wherehows-1.0-SNAPSHOT/RUNNING_PID
2. kill the process
kill -9 $pid
3. remove the RUNNING_PID file
rm /home/cloudera/wherehows/wherehows-1.0-SNAPSHOT/RUNNING_PID
4. using different command to start the font service
/home/cloudera/wherehows/wherehows-1.0-SNAPSHOT/bin/wherehows -Dhttp.port=9008

Let see if it works.

Thanks!

**Comment by hcove42** [comment]
Hi Jerry Bai

Just followed your instructions - but it didn't help.

The  file  "/home/cloudera/wherehows/runfrontend" contains the same line as you describe, and I assume that this is the file which is started automatically when the WM is launched?

Regards,
Hans Christian

**Comment by kevinrhaas** [comment]
Yes, followed the instructions from jerrybai2009 above and no change in behavior on login:

[ERROR] - from application in play-akka.actor.default-dispatcher-2 
Could not get JDBC Connection; nested exception is java.sql.SQLException: Unable to open a test connection to the given database. JDBC url = jdbc:mysql://172.21.98.60/wherehows?charset=utf8&zeroDateTimeBehavior=convertToNull, username = wherehows. Terminating connection pool (set lazyInit to true if you expect to start your database after your app). Original Exception: ------
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

**Comment by nbateshaus** [comment]
Following those instructions, I got the same failure. This, however, works:
```
/home/cloudera/wherehows/wherehows-1.0-SNAPSHOT/bin/wherehows -Dhttp.port=9008 -Ddatabase.opensource.url="jdbc:mysql://localhost/wherehows?charset=utf8&zeroDateTimeBehavior=convertToNull"
```

**Comment by hcove42** [comment]
Great - now it works ;-)

**Comment by kevinrhaas** [comment]
Thanks, @nbateshaus, that worked like a champ!

**Comment by taylorterry3** [comment]
Same here, thanks!

**Comment by ericsun2** [comment]
Thanks, @nbateshaus <https://github.com/nbateshaus>!

We have a new image posted. I have also mentioned the
database.opensource.url override in the readme file for download.

**Comment by SunZhaonan** [comment]
Thanks for @nbateshaus help. We found that the VM before March. 3 did have a hard code host name in the configure file. And that's inside the jar file in lib folder, that's why you can't grep it out. If you download after March. 4 it should works fine. 
Recently we have some new changes in the latest version, welcome to check it out!
