### ISSUE TITLE
wehrehows build error

### ISSUE THREAD

**Issue by diaowenyang** [linkedin/WhereHows#652]
[root@a WhereHows ] ./gradlew build --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wherehows-web:bowerInstall'.
> Process 'command '/root/WhereHows/wherehows-web/build/nodejs/node-v7.10.1-linux-x64/bin/node'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':wherehows-web:bowerInstall'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 27 more
BUILD FAILED in 1s

I am running this in a redhat7.0 server and I didn't find gradle.properties.
I don't figure is the problem here.
help is much appreciated.

**Comment by mars-lan** [comment]
Can you try "./gradlew clean" then "./gradle build" again?

**Comment by diaowenyang** [comment]
Thanks @mars-lan 
I tried it on your suggestion，but it didn't work.
Can I get any else help？
Thank you very much！

**Comment by mars-lan** [comment]
Can you also provide the output of  ./gradlew build --debug? Thanks.

**Comment by mars-lan** [comment]
> 09:10:24.617 [ERROR] [system.err] make: Entering directory /root/wh_soft/WhereHows/wherehows-web/node_modules/node-sass/build' 09:10:24.617 [ERROR] [system.err] g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.5.0.beta.2"' -I/root/.node-gyp/7.10.1/include/node -I/root/.node-gyp/7.10.1/src -I/root/.node-gyp/7.10.1/deps/uv/include -I/root/.node-gyp/7.10.1/deps/v8/include -I../src/libsass/include -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp 09:10:24.617 [ERROR] [system.err] make: g++: Command not found 09:10:24.617 [ERROR] [system.err] make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 127 09:10:24.617 [ERROR] [system.err] make: Leaving 

Looks like you're missing g++. Please install it via `yum install gcc-c++`

**Comment by diaowenyang** [comment]
Thanks @mars-lan 
Your solution is very useful.But I met a new question.My network is not very good:https://nodejs.org:443.
Can I get any else help？Thank you very much!


22:59:38.902 [DEBUG] [org.apache.http.impl.conn.DefaultHttpClientConnectionOperator] Connect to nodejs.org/104.20.23.46:443 timed out. Connection will be retried using another IP address
22:59:38.902 [DEBUG] [org.apache.http.impl.conn.DefaultHttpClientConnectionOperator] Connecting to nodejs.org/2400:cb00:2048:1:0:0:6814:172e:443
22:59:38.902 [DEBUG] [org.apache.http.conn.ssl.SSLConnectionSocketFactory] Connecting socket to nodejs.org/2400:cb00:2048:1:0:0:6814:172e:443 with timeout 0
22:59:38.903 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-56: Shutdown connection
22:59:38.903 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Connection discarded
22:59:38.903 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-56: Close connection
22:59:38.903 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection released: [id: 56][route: {s}->https://nodejs.org:443][total kept alive: 0; route allocated: 0 of 20; total allocated: 0 of 20]
22:59:38.903 [INFO] [org.apache.http.impl.execchain.RetryExec] I/O exception (java.net.SocketException) caught when processing request to {s}->https://nodejs.org:443: Network is unreachable (connect failed)
22:59:38.903 [DEBUG] [org.apache.http.impl.execchain.RetryExec] Network is unreachable (connect failed)
java.net.SocketException: Network is unreachable (connect failed)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:133)
        at org.gradle.internal.resource.transport.http.HttpClientHelper.performHttpRequest(HttpClientHelper.java:119)
        at org.gradle.internal.resource.transport.http.HttpClientHelper.executeGetOrHead(HttpClientHelper.java:96)
        at org.gradle.internal.resource.transport.http.HttpClientHelper.performRequest(HttpClientHelper.java:87)
        at org.gradle.internal.resource.transport.http.HttpClientHelper.performRawGet(HttpClientHelper.java:73)
        at org.gradle.internal.resource.transport.http.HttpClientHelper.performGet(HttpClientHelper.java:77)
        at org.gradle.internal.resource.transport.http.HttpResourceAccessor.openResource(HttpResourceAccessor.java:43)
        at org.gradle.internal.resource.transport.http.HttpResourceAccessor.openResource(HttpResourceAccessor.java:29)
        at org.gradle.internal.resource.transfer.DefaultExternalResourceConnector.openResource(DefaultExternalResourceConnector.java:56)
        at org.gradle.internal.resource.transfer.ProgressLoggingExternalResourceAccessor.openResource(ProgressLoggingExternalResourceAccessor.java:36)
        at org.gradle.internal.resource.transfer.AccessorBackedExternalResource.withContentIfPresent(AccessorBackedExternalResource.java:130)
        at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$11.call(BuildOperationFiringExternalResourceDecorator.java:237)
        at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$11.call(BuildOperationFiringExternalResourceDecorator.java:229)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:331)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:321)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:105)
        at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator.withContentIfPresent(BuildOperationFiringExternalResourceDecorator.java:229)
        at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.copyToCache(DefaultCacheAwareExternalResourceAccessor.java:196)
        at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.access$300(DefaultCacheAwareExternalResourceAccessor.java:55)
        at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$1.create(DefaultCacheAwareExternalResourceAccessor.java:88)
        at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor$1.create(DefaultCacheAwareExternalResourceAccessor.java:80)
        at org.gradle.cache.internal.DefaultProducerGuard.guardByKey(DefaultProducerGuard.java:51)
        at org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor.getResource(DefaultCacheAwareExternalResourceAccessor.java:80)
        at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.downloadStaticResource(DefaultExternalResourceArtifactResolver.java:97)
        at org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver.resolveArtifact(DefaultExternalResourceArtifactResolver.java:65)
        at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver.parseMetaDataFromArtifact(ExternalResourceResolver.java:213)
        at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver.resolveStaticDependency(ExternalResourceResolver.java:190)
        at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver.doResolveComponentMetaData(ExternalResourceResolver.java:186)
        at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver$RemoteRepositoryAccess.resolveComponentMetaData(ExternalResourceResolver.java:485)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$ResolveAndCacheRepositoryAccess.resolveComponentMetaData(CachingModuleComponentRepository.java:363)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.BaseModuleComponentRepositoryAccess.resolveComponentMetaData(BaseModuleComponentRepositoryAccess.java:50)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedModuleComponentRepository$CachedAccess.resolveComponentMetaData(InMemoryCachedModuleComponentRepository.java:95)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.resolveComponentMetaData(ErrorHandlingModuleComponentRepository.java:109)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ComponentMetaDataResolveState.process(ComponentMetaDataResolveState.java:66)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ComponentMetaDataResolveState.resolve(ComponentMetaDataResolveState.java:58)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.findBestMatch(RepositoryChainComponentMetaDataResolver.java:133)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.findBestMatch(RepositoryChainComponentMetaDataResolver.java:116)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:89)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolve(RepositoryChainComponentMetaDataResolver.java:60)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ComponentMetaDataResolverChain.resolve(ComponentResolversChain.java:93)
        at org.gradle.api.internal.artifacts.ivyservice.clientmodule.ClientModuleResolver.resolve(ClientModuleResolver.java:45)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$ComponentState.resolve(DependencyGraphBuilder.java:854)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$ComponentState.getMetaData(DependencyGraphBuilder.java:865)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$EdgeState.calculateTargetConfigurations(DependencyGraphBuilder.java:446)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder$EdgeState.attachToTargetConfigurations(DependencyGraphBuilder.java:417)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.attachToTargetRevisionsSerially(DependencyGraphBuilder.java:223)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolveEdges(DependencyGraphBuilder.java:213)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:148)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:121)
        at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:86)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveGraph(DefaultConfigurationResolver.java:138)
        at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:73)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:66)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$4.run(DefaultConfiguration.java:469)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:461)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:437)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1600(DefaultConfiguration.java:114)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:865)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:853)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:382)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolve(DefaultConfiguration.java:378)
        at org.gradle.api.artifacts.Configuration$resolve.call(Unknown Source)
        at com.moowork.gradle.node.task.SetupTask.resolveSingle(SetupTask.groovy:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
        at com.moowork.gradle.node.task.SetupTask.getNodeArchiveFile(SetupTask.groovy:152)
        at com.moowork.gradle.node.task.SetupTask_Decorated.getNodeArchiveFile(Unknown Source)
        at com.moowork.gradle.node.task.SetupTask.unpackNodeArchive(SetupTask.groovy:93)
        at com.moowork.gradle.node.task.SetupTask.exec(SetupTask.groovy:77)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:711)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:242)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:612)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:567)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:745)
22:59:38.904 [INFO] [org.apache.http.impl.execchain.RetryExec] Retrying request to {s}->https://nodejs.org:443
22:59:38.904 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: default
22:59:38.904 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
22:59:38.904 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection request: [route: {s}->https://nodejs.org:443][total kept alive: 0; route allocated: 0 of 20; total allocated: 0 of 20]
22:59:38.905 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection leased: [id: 57][route: {s}->https://nodejs.org:443][total kept alive: 0; route allocated: 1 of 20; total allocated: 1 of 20]

**Comment by mars-lan** [comment]
It is expected to be stuck for as long as the server is running. You should be able to access the site by opening http://localhost:9001 when you see the following line

[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9001

I'm going to close this issue now. Feel free to re-open if you have other build-related questions.

**Comment by EmnaDr** [comment]
hello, i'm trying to build wherehows version 1.0.0 but in vain
failed at building the web application
:wherehows-web:emberBuild , can you please help me out in this?
i have downloaded the pre release wherehows 1.0.0
https://github.com/linkedin/WhereHows/releases/tag/v1.0.0

**Comment by EmnaDr** [comment]
@mars-lan  can you please check?

**Comment by EmnaDr** [comment]
16:54:46.073 [QUIET] [system.out] Build failed.
16:54:46.073 [ERROR] [system.err] The Broccoli Plugin: [EyeglassCompiler: EyeglassCompiler: wherehows-web] failed with:
16:54:46.074 [ERROR] [system.err] Error: B
    at undefined:undefined:undefined
    at G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\broccoli-eyeglass\lib\broccoli_sass_compiler.js:667:11
    at Object.finallyHandler (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\bluebird\js\main\finally.js:39:23)
    at Object.tryCatcher (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromises (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)


The broccoli plugin was instantiated at:
    at EyeglassCompiler.Plugin (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\broccoli-plugin\index.js:7:31)
    at EyeglassCompiler.BroccoliSassCompiler [as constructor] (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\broccoli-eyeglass\lib\broccoli_sass_compiler.js:193:18)
    at new EyeglassCompiler (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\broccoli-eyeglass\lib\index.js:56:24)
    at Object.toTree (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli-eyeglass\index.js:132:16)
    at G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli-preprocess-registry\preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli-preprocess-registry\preprocessors.js:178:11)
    at module.exports.preprocessCss (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli-preprocess-registry\preprocessors.js:148:10)
    at EmberApp.styles (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli\lib\broccoli\ember-app.js:1346:28)
    at EmberApp.toArray (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli\lib\broccoli\ember-app.js:1675:10)
    at EmberApp.toTree (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli\lib\broccoli\ember-app.js:1696:30)
    at module.exports (G:\DevSrc\WhereHows-1.0.0\wherehows-web\ember-cli-build.js:134:14)
    at Class.setupBroccoliBuilder (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli\lib\models\builder.js:84:19)
    at Class.init (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli\lib\models\builder.js:64:10)
    at Class.superWrapper [as init] (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\core-object\lib\assign-properties.js:32:18)
    at Class (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\core-object\core-object.js:32:33)
    at Class.run (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli\lib\tasks\build.js:15:19)
    at G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli\lib\commands\build.js:32:24
    at tryCatch (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\rsvp\dist\rsvp.js:554:13)
    at publish (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\rsvp\dist\rsvp.js:522:7)
    at flush (G:\DevSrc\WhereHows-1.0.0\wherehows-web\node_modules\rsvp\dist\rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
