### ISSUE TITLE
run oraclemeta ERROR Job ： create PyString with non-byte value

### ISSUE THREAD

**Issue by wzfxue** [linkedin/WhereHows#754]
2017-09-19 11:35:54 INFO  jython script : OracleExtract:-2 - Collecting table info [11:34:38 -> 11:35:54]
2017-09-19 11:35:57 ERROR Job Launcher:87 - Traceback (most recent call last):
  File "<iostream>", line 372, in <module>
  File "<iostream>", line 330, in run
  File "<iostream>", line 301, in write_csv
  File "/home/cloudera/wherehows/backend-service-1.0-SNAPSHOT/lib/org.python-jython-standalone-2.7.0.jar/Lib/csv.py", line 148, in writerow
java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
	at org.python.core.PyString.<init>(PyString.java:64)
	at org.python.core.PyString.<init>(PyString.java:70)
	at org.python.modules._csv.PyWriter.writer_writerow(PyWriter.java:167)
	at org.python.modules._csv.PyWriter$writer_writerow_exposer.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at csv$py.writerow$16(/home/cloudera/wherehows/backend-service-1.0-SNAPSHOT/lib/org.python-jython-standalone-2.7.0.jar/Lib/csv.py:148)
	at csv$py.call_function(/home/cloudera/wherehows/backend-service-1.0-SNAPSHOT/lib/org.python-jython-standalone-2.7.0.jar/Lib/csv.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at org.python.pycode._pyx0.write_csv$10(<iostream>:302)
	at org.python.pycode._pyx0.call_function(<iostream>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:188)
	at org.python.core.PyFunction.__call__(PyFunction.java:446)
	at org.python.core.PyMethod.__call__(PyMethod.java:171)
	at org.python.pycode._pyx0.run$11(<iostream>:340)
	at org.python.pycode._pyx0.call_function(<iostream>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.pycode._pyx0.f$0(<iostream>:380)
	at org.python.pycode._pyx0.call_function(<iostream>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:291)
	at metadata.etl.JythonEtlJob.runScript(JythonEtlJob.java:64)
	at metadata.etl.JythonEtlJob.extract(JythonEtlJob.java:35)
	at metadata.etl.EtlJob.run(EtlJob.java:97)
	at wherehows.common.jobs.Launcher.main(Launcher.java:82)

java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value

	at org.python.core.Py.JavaError(Py.java:546)
	at org.python.core.PyTableCode.call(PyTableCode.java:170)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at org.python.pycode._pyx0.write_csv$10(<iostream>:302)
	at org.python.pycode._pyx0.call_function(<iostream>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:188)
	at org.python.core.PyFunction.__call__(PyFunction.java:446)
	at org.python.core.PyMethod.__call__(PyMethod.java:171)
	at org.python.pycode._pyx0.run$11(<iostream>:340)
	at org.python.pycode._pyx0.call_function(<iostream>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.pycode._pyx0.f$0(<iostream>:380)
	at org.python.pycode._pyx0.call_function(<iostream>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:291)
	at metadata.etl.JythonEtlJob.runScript(JythonEtlJob.java:64)
	at metadata.etl.JythonEtlJob.extract(JythonEtlJob.java:35)
	at metadata.etl.EtlJob.run(EtlJob.java:97)
	at wherehows.common.jobs.Launcher.main(Launcher.java:82)
Caused by: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
	at org.python.core.PyString.<init>(PyString.java:64)
	at org.python.core.PyString.<init>(PyString.java:70)
	at org.python.modules._csv.PyWriter.writer_writerow(PyWriter.java:167)
	at org.python.modules._csv.PyWriter$writer_writerow_exposer.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at csv$py.writerow$16(/home/cloudera/wherehows/backend-service-1.0-SNAPSHOT/lib/org.python-jython-standalone-2.7.0.jar/Lib/csv.py:148)
	at csv$py.call_function(/home/cloudera/wherehows/backend-service-1.0-SNAPSHOT/lib/org.python-jython-standalone-2.7.0.jar/Lib/csv.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	... 28 more

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
