### ISSUE TITLE
Hive Metadata ETL Error on master branch

### ISSUE THREAD

**Issue by diaowenyang** [linkedin/WhereHows#768]
2017-09-26 07:08:15 INFO  application:55 - Creating Pool for datasource 'wherehows'
2017-09-26 07:08:15 INFO  p.a.d.DefaultDBApi:45 - Database [wherehows] connected at jdbc:mysql://10.254.10.62:3306/wherehows?charset=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
2017-09-26 07:08:16 INFO  application:34 - on start---===
2017-09-26 07:08:16 INFO  p.a.Play:97 - Application started (Dev)
2017-09-26 07:08:16 INFO  application:65 - Enabled jobs: [HIVE_METADATA_ETL]
2017-09-26 07:08:16 INFO  application:58 - Kafka jobs: []
2017-09-26 07:08:16 INFO  application:146 - Terminating KafkaConsumerMaster...
2017-09-26 07:08:16 INFO  application:68 - Scheduled jobs: {HIVE_METADATA_ETL=1506330600}
2017-09-26 07:08:16 INFO  application:86 - Running job: HIVE_METADATA_ETL
2017-09-26 07:08:16 INFO  application:95 - Current running jobs : 
2017-09-26 07:08:16 INFO  application:102 - Send message : (jobName:HIVE_METADATA_ETL, whEtlExecId:28)
2017-09-26 07:08:16 DEBUG application:70 - run command : [java, -cp, , -Dconfig=/home/wherehows/Documents/etl/temp/exec/28.properties, -DCONTEXT=HIVE_METADATA_ETL, -Dlogback.configurationFile=etl_logback.xml, -DLOG_DIR=/home/wherehows/Documents/etl/temp, wherehows.common.jobs.Launcher] ; timeout: 12000
2017-09-26 07:08:16 ERROR application:119 - *** Process + 1210 failed, status: 1
2017-09-26 07:08:16 ERROR application:120 - Error Details:

java.lang.Exception: Process + 1210 failed
        at actors.EtlJobActor.onReceive(EtlJobActor.java:121)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2017-09-26 07:08:16 ERROR application:136 - ETL job (jobName:HIVE_METADATA_ETL, whEtlExecId:28) got a problem
2017-09-26 07:13:16 INFO  application:65 - Enabled jobs: [HIVE_METADATA_ETL]
2017-09-26 07:13:16 INFO  application:68 - Scheduled jobs: {HIVE_METADATA_ETL=1506381000}
2017-09-26 07:13:16 INFO  application:86 - Running job: HIVE_METADATA_ETL
2017-09-26 07:13:16 INFO  application:95 - Current running jobs : 
2017-09-26 07:13:16 INFO  application:102 - Send message : (jobName:HIVE_METADATA_ETL, whEtlExecId:29)
2017-09-26 07:13:16 DEBUG application:70 - run command : [java, -cp, , -Dconfig=/home/wherehows/Documents/etl/temp/exec/29.properties, -DCONTEXT=HIVE_METADATA_ETL, -Dlogback.configurationFile=etl_logback.xml, -DLOG_DIR=/home/wherehows/Documents/etl/temp, wherehows.common.jobs.Launcher] ; timeout: 12000
2017-09-26 07:13:16 ERROR application:119 - *** Process + 5282 failed, status: 1
2017-09-26 07:13:16 ERROR application:120 - Error Details:

java.lang.Exception: Process + 5282 failed
        at actors.EtlJobActor.onReceive(EtlJobActor.java:121)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2017-09-26 07:13:16 ERROR application:136 - ETL job (jobName:HIVE_METADATA_ETL, whEtlExecId:29) got a problem
2017-09-26 07:18:16 INFO  application:65 - Enabled jobs: [HIVE_METADATA_ETL]
2017-09-26 07:18:16 INFO  application:68 - Scheduled jobs: {HIVE_METADATA_ETL=1506384600}
2017-09-26 07:23:16 INFO  application:65 - Enabled jobs: [HIVE_METADATA_ETL]
2017-09-26 07:23:16 INFO  application:68 - Scheduled jobs: {HIVE_METADATA_ETL=1506384600}
2017-09-26 07:28:16 INFO  application:65 - Enabled jobs: [HIVE_METADATA_ETL]
2017-09-26 07:28:16 INFO  application:68 - Scheduled jobs: {HIVE_METADATA_ETL=1506384600}

**Comment by rilma** [comment]
Does it look familiar this error message? I am getting it after I place the job script in the job folder then run "./runBackend"

java.lang.Exception: Process + 6905 failed
        at actors.EtlJobActor.onReceive(EtlJobActor.java:125)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2017-11-24 11:09:15 ERROR application:140 - ETL job (jobName:CCP_HIVE_METADATA_ETL, whEtlExecId:27) got a problem

**Comment by diaowenyang** [comment]
@rilma  
find in wherehows-backend/conf/application.conf，and get the value ：etl.temp.dir 
Go to that path to find more logs.

**Comment by renzehello** [comment]
How to fix this issue please？
