### ISSUE TITLE
build fail: Error: File to read not found or unreadable:   wherehows-web/tmp/eyeglass_.../app/styles/app.scss

### ISSUE THREAD

**Issue by liqingrikeiikyeong** [linkedin/WhereHows#855]
09:49:00.141 [QUIET] [system.out] Build failed.
The Broccoli Plugin: [EyeglassCompiler: EyeglassCompiler: wherehows-web] failed with:

09:49:00.141 [ERROR] [system.err] Error: File to read not found or unreadable: 

D:/Developer/code_repo/talking_data/WhereHows-1.0.0/wherehows-web/tmp/eyeglass_compiler-input_base_path-axmZP6FC.tmp/D:/Developer/code_repo/talking_data/WhereHows-1.0.0/wherehows-web/tmp/eyeglass_compiler-input_base_path-axmZP6FC.tmp/app/styles/app.scss
    at undefined:undefined:undefined
    at D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\broccoli-eyeglass\lib\broccoli_sass_compiler.js:667:11
    at Object.finallyHandler (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\bluebird\js\main\finally.js:39:23)
    at Object.tryCatcher (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromises (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

The broccoli plugin was instantiated at: 
    at EyeglassCompiler.Plugin (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\broccoli-plugin\index.js:7:31)
    at EyeglassCompiler.BroccoliSassCompiler [as constructor] (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\broccoli-eyeglass\lib\broccoli_sass_compiler.js:193:18)
    at new EyeglassCompiler (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\broccoli-eyeglass\lib\index.js:56:24)
    at Object.toTree (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli-eyeglass\index.js:132:16)
    at D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli-preprocess-registry\preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli-preprocess-registry\preprocessors.js:178:11)
    at module.exports.preprocessCss (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli-preprocess-registry\preprocessors.js:148:10)
    at EmberApp.styles (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli\lib\broccoli\ember-app.js:1346:28)
    at EmberApp.toArray (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli\lib\broccoli\ember-app.js:1675:10)
    at EmberApp.toTree (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli\lib\broccoli\ember-app.js:1696:30)
    at module.exports (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\ember-cli-build.js:134:14)
    at Class.setupBroccoliBuilder (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli\lib\models\builder.js:84:19)
    at Class.init (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli\lib\models\builder.js:64:10)
    at Class.superWrapper [as init] (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\core-object\lib\assign-properties.js:32:18)
    at Class (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\core-object\core-object.js:32:33)
    at Class.run (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli\lib\tasks\build.js:15:19)
    at D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\ember-cli\lib\commands\build.js:32:24
    at tryCatch (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\rsvp\dist\rsvp.js:554:13)
    at publish (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\rsvp\dist\rsvp.js:522:7)
    at flush (D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\node_modules\rsvp\dist\rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

09:49:00.187 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
09:49:00.187 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\build\nodejs\node-v7.8.0-win-x64\node.exe'' finished with exit value 1 (state: FAILED)
09:49:00.188 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':wherehows-web:emberBuild'
09:49:00.188 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :wherehows-web:emberBuild FAILED
09:49:00.192 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 25: dispatching class org.gradle.launcher.daemon.protocol.BuildEvent
09:49:00.195 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :wherehows-web:emberBuild (Thread[Daemon worker Thread 2,5,main]) completed. Took 4 mins 1.946 secs.
09:49:00.195 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 2,5,main]] finished, busy: 13 mins 44.809 secs, idle: 0.033 secs
09:49:00.197 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 25: dispatching class org.gradle.launcher.daemon.protocol.BuildEvent
09:49:00.211 [ERROR] [org.gradle.BuildExceptionReporter] 
09:49:00.211 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
09:49:00.211 [ERROR] [org.gradle.BuildExceptionReporter] 
09:49:00.211 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
09:49:00.211 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':wherehows-web:emberBuild'.
09:49:00.212 [ERROR] [org.gradle.BuildExceptionReporter] > Process 'command 'D:\Developer\code_repo\talking_data\WhereHows-1.0.0\wherehows-web\build\nodejs\node-v7.8.0-win-x64\node.exe'' finished with non-zero exit value 1
09:49:00.212 [ERROR] [org.gradle.BuildExceptionReporter] 
09:49:00.212 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
09:49:00.212 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
09:49:00.213 [LIFECYCLE] [org.gradle.BuildResultLogger]

**Comment by liqingrikeiikyeong** [comment]
https://ember-cli.com/user-guide/#windows

window ember cli issue

**Comment by diaowenyang** [comment]
@liqingrikeiikyeong 上面的报错是如何修复的？
