### ISSUE TITLE
zxJDBC.Error: ERROR: relation "dbs" does not exist

### ISSUE THREAD

**Issue by sagartoms** [linkedin/WhereHows#872]
I am getting the following error while trying to run the HIVE_METADATA_ETL_JOB using **postgresql** metastore.

zxJDBC.Error: ERROR: relation "dbs" does not exist
  Position: 20 [SQLCode: 0], [SQLState: 42P01]

        at org.python.core.PyException.doRaise(PyException.java:198)
        at org.python.core.Py.makeException(Py.java:1337)
        at org.python.core.Py.makeException(Py.java:1341)
        at com.ziclix.python.sql.zxJDBC.makeException(zxJDBC.java:329)
        at com.ziclix.python.sql.zxJDBC.makeException(zxJDBC.java:411)
        at com.ziclix.python.sql.zxJDBC.makeException(zxJDBC.java:367)
        at com.ziclix.python.sql.zxJDBC.makeException(zxJDBC.java:356)
        at com.ziclix.python.sql.PyCursor.execute(PyCursor.java:611)
...................

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
