### ISSUE TITLE
HdfsMetadataEtl error

### ISSUE THREAD

**Issue by diaowenyang** [linkedin/WhereHows#881]
HI:
I use wherehows v1.0.0.
When I configure HDFS_METADATA_ETL.job to load hdfs metadata to wherehows.
I meet those errors:
2017-11-26 22:15:19 INFO  Redirect schemaFetch output : :46 - Exception in thread "main" java.lang.UnsupportedClassVersionError: wherehows/SchemaFetch : Unsupported major.minor version 52.0
2017-11-26 22:15:19 INFO  Redirect schemaFetch output : :46 - 	at java.lang.ClassLoader.defineClass1(Native Method)
2017-11-26 22:15:19 INFO  Redirect schemaFetch output : :46 - 	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
2017-11-26 22:15:19 INFO  Redirect schemaFetch output : :46 - 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2017-11-26 22:15:19 INFO  Redirect schemaFetch output : :46 - 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
2017-11-26 22:15:19 INFO  Redirect schemaFetch output : :46 - 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
2017-11-26 22:15:19 INFO  Redirect schemaFetch output : :46 - 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
2017-11-26 22:15:19 INFO  Redirect schemaFetch output : :46 - 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
2017-11-26 22:15:19 INFO  Redirect schemaFetch output : :46 - 	at java.security.AccessController.doPrivileged(Native Method)
2017-11-26 22:15:19 INFO  Redirect schemaFetch output : :46 - 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
2017-11-26 22:15:19 INFO  Redirect schemaFetch output : :46 - 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
2017-11-26 22:15:19 INFO  Redirect schemaFetch output : :46 - 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
2017-11-26 22:15:19 INFO  Redirect schemaFetch output : :46 - 	at java.lang.Class.forName0(Native Method)
2017-11-26 22:15:19 INFO  Redirect schemaFetch output : :46 - 	at java.lang.Class.forName(Class.java:278)
2017-11-26 22:15:19 INFO  Redirect schemaFetch output : :46 - 	at org.apache.hadoop.util.RunJar.run(RunJar.java:214)
2017-11-26 22:15:19 INFO  Redirect schemaFetch output : :46 - 	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
2017-11-26 22:15:20 INFO  m.e.d.h.HdfsMetadataEtl:279 - ExecChannel exit-status: 1
2017-11-26 22:15:20 INFO  m.e.d.h.HdfsMetadataEtl:288 - extract finished
2017-11-26 22:15:20 INFO  m.e.d.h.HdfsMetadataEtl:304 - Begin hdfs metadata transform : 20784
2017-11-26 22:15:20 INFO  m.e.d.h.HdfsMetadataEtl:315 - Begin hdfs metadata load : 20784
2017-11-26 22:15:21 INFO  HdfsLoad:20784:-2 - finish loading hdfs metadata db_id=11 to dict_dataset

I google it ,some answers mean,it should choose jdk1.8.  But my version is 1.8.0_121.

And I use remote mode. Can anyone tell me how to fix it，thank you very much!

**Comment by LeeMo2K10** [comment]
show HDFS_METADATA_ETL.job
