### ISSUE TITLE
 m.e.JythonEtlJob:62 - Launching jython script jython/OracleExtract.py

### ISSUE THREAD

**Issue by liyaqiu** [linkedin/WhereHows#900]
I tried to change to the East eight, or would I make a mistake

2017-12-07 03:20:40 ERROR w.c.j.Launcher:87 - Traceback (most recent call last):
  File "<iostream>", line 353, in <module>
zxJDBC.DatabaseError: ORA-00604: error occurred at recursive SQL level 1
ORA-01882: timezone region not found
 [SQLCode: 604], [SQLState: 60000]

        at org.python.core.PyException.doRaise(PyException.java:198)
        at org.python.core.Py.makeException(Py.java:1337)
        at org.python.core.Py.makeException(Py.java:1341)
        at com.ziclix.python.sql.zxJDBC.makeException(zxJDBC.java:329)
        at com.ziclix.python.sql.zxJDBC.makeException(zxJDBC.java:411)
        at com.ziclix.python.sql.zxJDBC.makeException(zxJDBC.java:367)
        at com.ziclix.python.sql.connect.Connect.__call__(Connect.java:85)
        at org.python.core.PyObject.__call__(PyObject.java:515)
        at org.python.core.PyObject.__call__(PyObject.java:521)
        at org.python.pycode._pyx0.f$0(<iostream>:380)
        at org.python.pycode._pyx0.call_function(<iostream>)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyCode.call(PyCode.java:18)
        at org.python.core.Py.runCode(Py.java:1386)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:291)
        at metadata.etl.JythonEtlJob.runScript(JythonEtlJob.java:65)
        at metadata.etl.JythonEtlJob.extract(JythonEtlJob.java:36)
        at metadata.etl.EtlJob.run(EtlJob.java:112)
        at wherehows.common.jobs.Launcher.main(Launcher.java:82)

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
