### ISSUE TITLE
Oozie unable to collect flow schedules

### ISSUE THREAD

**Issue by visokoo** [linkedin/WhereHows#903]
Hey there, 

I'm trying wherehows in a docker environment and am trying to just get it to collect Oozie metrics to start. Based on the log, it looks like all the steps from the OozieExtract are working except for collect_flow_schedule. It keeps dying with this error:

```root@9b6cb531096f:/application/logs/etl/OOZIE_EXECUTION_METADATA_ETL/6# more log
2017-12-07 23:10:58 INFO  m.e.EtlJob:111 - PySystem path: ['/application/lib/Lib', '/application/lib/org.python-jython-standalone-2.7.0.jar/Lib', '__classpath__', '__pyclasspath__/', '/application/lib/wherehows-etl-wherehows-etl.jar/jython']
2017-12-07 23:10:58 INFO  m.e.JythonEtlJob:62 - Launching jython script jython/OozieExtract.py
2017-12-07 23:11:00 INFO  jython script : OozieExtract:-2 - Oozie version:
2017-12-07 23:11:00 INFO  jython script : OozieExtract:-2 - collect flow&jobs
2017-12-07 23:11:11 INFO  jython script : OozieExtract:-2 - collect owners
2017-12-07 23:11:11 INFO  jython script : OozieExtract:-2 - collect flow schedule
2017-12-07 23:11:11 ERROR w.c.j.Launcher:87 - Traceback (most recent call last):  File "<iostream>", line 228, in <module>
  File "<iostream>", line 66, in run
  File "<iostream>", line 162, in collect_flow_schedules
ValueError: invalid literal for int() with base 10: '20 20 * * *'

	at org.python.core.Py.ValueError(Py.java:333)
	at org.python.core.PyString.atoi(PyString.java:2895)
	at org.python.core.PyUnicode.atoi(PyUnicode.java:1905)
	at org.python.core.PyString.__int__(PyString.java:1007)
	at org.python.core.PyInteger.asPyInteger(PyInteger.java:127)
	at org.python.core.PyInteger.int_new(PyInteger.java:75)
        at org.python.core.PyInteger$exposed___new__.new_impl(Unknown Source)
	at org.python.core.PyType.invokeNew(PyType.java:494)
	at org.python.core.PyType.type___call__(PyType.java:1706)
	at org.python.core.PyType.__call__(PyType.java:1696)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.pycode._pyx0.collect_flow_schedules$7(<iostream>:173)
	at org.python.pycode._pyx0.call_function(<iostream>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at org.python.pycode._pyx0.run$4(<iostream>:71)
	at org.python.pycode._pyx0.call_function(<iostream>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.f$0(<iostream>:228)
	at org.python.pycode._pyx0.call_function(<iostream>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:291)
	at metadata.etl.JythonEtlJob.runScript(JythonEtlJob.java:65)
	at metadata.etl.JythonEtlJob.extract(JythonEtlJob.java:36)
	at metadata.etl.EtlJob.run(EtlJob.java:112)
	at wherehows.common.jobs.Launcher.main(Launcher.java:82)
```
Can anyone shed some light on this? I otherwise see data being collected for dag/flow/job/owner.csv. Thanks in advance for any help....

**Comment by visokoo** [comment]
Looks like it's failing on the wrong type being specified under `frequency`.

Following the code, the class is already expecting a string so not sure why it's being forcefully converted to an int in OozieExtract.py so I made a [PR](https://github.com/linkedin/WhereHows/pull/904) to fix that.

**Comment by visokoo** [comment]
Closing this issue since my PR was merged.
