### ISSUE TITLE
HDFS job ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by LeeMo2K10** [linkedin/WhereHows#907]
HDFS job : 
hdfs_raw_metadata.json
hdfs_raw_metadata.json.log
hdfs_sample.dat
three file is fire， but...
drwxr-xr-x 2 root root 4096 12月  9 10:10 exec
-rw-r--r-- 1 root root 3627 12月  9 10:10 HDFS_METADATA_ETL.log
-rw-r--r-- 1 root root    0 12月  9 10:10 HDFS_METADATA_ETL.stderr
-rw-r--r-- 1 root root    0 12月  9 10:10 HDFS_METADATA_ETL.stdout
-rw-r--r-- 1 root root 1645 12月  9 10:10 hdfs_raw_metadata.json
-rw-r--r-- 1 root root  946 12月  9 10:10 hdfs_raw_metadata.json.log
-rw-r--r-- 1 root root 8471 12月  9 10:10 hdfs_sample.dat
[root@t1s2 wherehows]# more HDFS_METADATA_ETL.log 
2017-12-09 10:10:17 INFO  m.e.d.h.HdfsMetadataEtl:178 - PySystem path: ['/home/govnetapp/wherehows-backend/lib/Lib', '/home/govnetapp/wherehows-backend/lib/org.pytho
n-jython-standalone-2.7.0.jar/Lib', '__classpath__', '__pyclasspath__/', '/home/govnetapp/wherehows-backend/lib/wherehows-etl-wherehows-etl.jar/jython']
2017-12-09 10:10:17 INFO  m.e.d.h.HdfsMetadataEtl:71 - Begin hdfs metadata extract! - 88
2017-12-09 10:10:18 INFO  m.e.d.h.HdfsMetadataEtl:128 - executue command [PID=5885]: [Ljava.lang.String;@73fb1d7f
2017-12-09 10:10:21 INFO  m.e.d.h.HdfsMetadataEtl:249 - Begin hdfs metadata transform : 88
2017-12-09 10:10:21 ERROR Job Launcher:91 - Traceback (most recent call last):
  File "<iostream>", line 153, in <module>
  File "/home/govnetapp/wherehows-backend/lib/org.python-jython-standalone-2.7.0.jar/Lib/json/__init__.py", line 338, in loads
  File "/home/govnetapp/wherehows-backend/lib/org.python-jython-standalone-2.7.0.jar/Lib/json/decoder.py", line 365, in decode
  File "/home/govnetapp/wherehows-backend/lib/org.python-jython-standalone-2.7.0.jar/Lib/json/decoder.py", line 383, in raw_decode
ValueError: No JSON object could be decoded

        at org.python.core.PyException.doRaise(PyException.java:233)
        at org.python.core.Py.makeException(Py.java:1565)
        at org.python.core.Py.makeException(Py.java:1569)
        at org.python.core.Py.makeException(Py.java:1573)
        at json.decoder$py.raw_decode$10(/home/govnetapp/wherehows-backend/lib/org.python-jython-standalone-2.7.0.jar/Lib/json/decoder.py:384)
        at json.decoder$py.call_function(/home/govnetapp/wherehows-backend/lib/org.python-jython-standalone-2.7.0.jar/Lib/json/decoder.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:199)
        at org.python.core.PyFunction.__call__(PyFunction.java:482)
        at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
        at org.python.core.PyMethod.__call__(PyMethod.java:228)
        at json.decoder$py.decode$9(/home/govnetapp/wherehows-backend/lib/org.python-jython-standalone-2.7.0.jar/Lib/json/decoder.py:369)
        at json.decoder$py.call_function(/home/govnetapp/wherehows-backend/lib/org.python-jython-standalone-2.7.0.jar/Lib/json/decoder.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:146)
        at org.python.core.PyFunction.__call__(PyFunction.java:423)
        at org.python.core.PyMethod.__call__(PyMethod.java:141)
        at json$py.loads$4(/home/govnetapp/wherehows-backend/lib/org.python-jython-standalone-2.7.0.jar/Lib/json/__init__.py:351)
        at json$py.call_function(/home/govnetapp/wherehows-backend/lib/org.python-jython-standalone-2.7.0.jar/Lib/json/__init__.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:132)
        at org.python.core.PyFunction.__call__(PyFunction.java:413)
        at org.python.pycode._pyx0.f$0(<iostream>:157)
        at org.python.pycode._pyx0.call_function(<iostream>)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyCode.call(PyCode.java:18)
        at org.python.core.Py.runCode(Py.java:1614)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:291)
        at metadata.etl.dataset.hdfs.HdfsMetadataEtl.transform(HdfsMetadataEtl.java:252)
        at metadata.etl.EtlJob.run(EtlJob.java:180)
        at metadata.etl.Launcher.main(Launcher.java:86)

[root@t1s2 wherehows]#

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
