### ISSUE TITLE
KeyError: hive.metastore.reconnect.time

### ISSUE THREAD

**Issue by liyaqiu** [linkedin/WhereHows#909]
run  docker   error 

cat  /application/logs/etl/HIVE_METADATA_ETL/15/log   
2017-12-11 08:32:27 INFO  m.e.EtlJob:111 - PySystem path: ['/application/lib/Lib', '/application/lib/org.python-jython-standalone-2.7.0.jar/Lib', '__classpath__', '__pyclasspath__/', '/application/lib/wherehows-etl-wherehows-etl.jar/jython']
2017-12-11 08:32:27 INFO  m.e.d.h.HiveMetadataEtl:36 - In Hive metadata ETL, launch extract jython scripts
2017-12-11 08:32:32 ERROR w.c.j.Launcher:87 - Traceback (most recent call last):
  File "<iostream>", line 534, in <module>
  File "<iostream>", line 74, in __init__
KeyError: hive.metastore.reconnect.time

        at org.python.core.Py.KeyError(Py.java:249)
        at org.python.core.PyObject.__getitem__(PyObject.java:738)
        at org.python.pycode._pyx0.__init__$3(<iostream>:106)
        at org.python.pycode._pyx0.call_function(<iostream>)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
        at org.python.core.PyFunction.__call__(PyFunction.java:482)
        at org.python.core.PyFunction.__call__(PyFunction.java:476)
        at org.python.core.PyInstance.__init__(PyInstance.java:124)
        at org.python.core.PyClass.__call__(PyClass.java:193)
        at org.python.core.PyObject.__call__(PyObject.java:461)
        at org.python.core.PyObject.__call__(PyObject.java:465)
        at org.python.pycode._pyx0.f$0(<iostream>:545)
        at org.python.pycode._pyx0.call_function(<iostream>)
        at org.python.core.PyTableCode.call(PyTableCode.java:167)
        at org.python.core.PyCode.call(PyCode.java:18)
        at org.python.core.Py.runCode(Py.java:1386)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:291)
        at metadata.etl.dataset.hive.HiveMetadataEtl.extract(HiveMetadataEtl.java:43)
        at metadata.etl.EtlJob.run(EtlJob.java:112)
        at wherehows.common.jobs.Launcher.main(Launcher.java:82)

**Comment by keremsahin1** [comment]
Dear issue owner,

Thanks for your interest in WhereHows. We have recently announced DataHub which is the rebranding of WhereHows. LinkedIn improved the architecture of WhereHows and rebranded WhereHows into DataHub and replaced its metadata infrastructure in this direction. DataHub is a more advanced and improved metadata management product compared to WhereHows. 

Unfortunately, we have to stop supporting WhereHows to better focus on DataHub and offer more help to DataHub users. Therefore, we will drop all issues related to WhereHows and will not accept any contribution for it. Active development for DataHub has already started on `datahub` branch and will continue to live in there until it's finally merged to master and project is renamed to DataHub. 

Please check the `datahub` branch to get familar with DataHub.

Best,
DataHub team
