### ISSUE TITLE
Backend API : dataset POST API reporting error

### ISSUE THREAD

**Issue by leopoda** [linkedin/WhereHows#94]
execute dataset POST API from the backend API tutorial:

curl -H "Content-Type: application/json" -X POST -d '{"name" : "DUMMY4","urn" : "teradata:///DWH_TMP/DUMMY4","schema" : "{\"name\": \"DUMMY\", \"fields\": [{\"accessCount\": null, \"lastAccessTime\": null, \"nullable\": \"Y\", \"format\": null, \"type\": \"INT\", \"maxByteLength\": 4, \"name\": \"DUMMY\", \"doc\": \"\"}]}","properties" : "{\"storage_type\": \"View\", \"accessCount\": 2670, \"lastAccessTime\": null, \"sizeInMbytes\": null, \"referenceTables\": [\"DWH_DIM.DUMMY\"], \"viewSqlText\": \"REPLACE VIEW DWH_STG.DUMMY AS\nLOCKING ROW FOR ACCESS\n SELECT * \n   FROM DWH_DIM.DUMMY;\", \"createTime\": \"2015-03-06 10:43:58\", \"lastAlterTime\": \"2015-03-10 20:57:16\"}","schema_type" : "JSON","fields" :  "{\"DUMMY\": {\"type\": \"INT\", \"maxByteLength\": 4}}","source" : "Teradata","source_created_time" : null,"location_prefix" : "DWH_STG","ref_dataset_urn" : null,"is_partitioned" : "Y","sample_partition_full_path": null,"parent_name" : null,"storage_type" : null,"dataset_type" : null,"hive_serdes_class" : null}' http://localhost:19001/dataset

the backend web service response with below error message:

**{"return_code":404,"error_message":"Incorrect result size: expected 1, actual 0"}**

copy and paste the stack trace as below:

org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
	at org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:71)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:212)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:219)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForMap(NamedParameterJdbcTemplate.java:243)
	at models.daos.DatasetDao.getDatasetByUrn(DatasetDao.java:48)
	at models.daos.DatasetDao.insertDataset(DatasetDao.java:57)
	at controllers.DatasetController.addDataset(DatasetController.java:81)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$4$$anonfun$apply$4.apply(routes_routing.scala:205)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$4$$anonfun$apply$4.apply(routes_routing.scala:205)
	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183)
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56)
	at play.GlobalSettings$1.call(GlobalSettings.java:64)
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91)
	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90)
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:278)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:274)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by SunZhaonan** [comment]
This bug already resolved in #92 

You need to update to the latest version for your VM following :
https://github.com/linkedin/WhereHows/wiki/Quick-Start-with-VM#update-to-the-newest-version
