### ISSUE TITLE
wherehows-backend/jobs throws NPE

### ISSUE THREAD

**Issue by richardxin** [linkedin/WhereHows#965]
HI, I created hive ETL job and put it under wherehows-backend/jobs pretty much using the template with my own configurations.  (using mysql as hive metastore)

here is the error I got:

2018-02-14 21:43:36 INFO  application:55 - Creating Pool for datasource 'wherehows'
2018-02-14 21:43:36 INFO  p.a.d.DefaultDBApi:45 - Database [wherehows] connected at jdbc:mysql://wherehows-test-1.cwqfe0cyzte5.us-west-2.rds.amazonaws.com:3306/wherehows
2018-02-14 21:43:36 INFO  application:34 - on start---===
[ERROR] [02/14/2018 21:43:37.007] [WhereHowsETLService-akka.actor.default-dispatcher-8] [akka://WhereHowsETLService/user/TreeBuilderActor] null
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:166)
        at akka.actor.ActorCell.create(ActorCell.scala:596)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException
        at wherehows.common.utils.JobsUtil.getEnabledJobsByType(JobsUtil.java:122)
        at actors.TreeBuilderActor.preStart(TreeBuilderActor.java:55)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:472)
        at akka.actor.UntypedActor.aroundPreStart(UntypedActor.scala:97)
        at akka.actor.ActorCell.create(ActorCell.scala:580)
        ... 9 more

2018-02-14 21:43:37 INFO  p.a.Play:97 - Application started (Dev)
[ERROR] [02/14/2018 21:43:37.015] [WhereHowsETLService-akka.actor.default-dispatcher-3] [akka://WhereHowsETLService/user/SchedulerActor] null
java.lang.NullPointerException
        at wherehows.common.utils.JobsUtil.getScheduledJobs(JobsUtil.java:88)
        at actors.SchedulerActor.runDueJobs(SchedulerActor.java:66)
        at actors.SchedulerActor.onReceive(SchedulerActor.java:47)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2018-02-14 21:43:38 INFO  application:60 - Creating DAO factory: wherehows.dao.DaoFactory
[ERROR] [02/14/2018 21:48:37.025] [WhereHowsETLService-akka.actor.default-dispatcher-9] [akka://WhereHowsETLService/user/SchedulerActor] null
java.lang.NullPointerException
        at wherehows.common.utils.JobsUtil.getScheduledJobs(JobsUtil.java:88)
        at actors.SchedulerActor.runDueJobs(SchedulerActor.java:66)
        at actors.SchedulerActor.onReceive(SchedulerActor.java:47)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by richardxin** [comment]
not issue any more with tag v1.1.0

**Comment by yinsong** [comment]
@richardxin i have same error in tag1.1.0,how can i slove it 
[ERROR] [11/19/2018 09:51:06.859] [WhereHowsETLService-akka.actor.default-dispatcher-2946] [akka://WhereHowsETLService/user/SchedulerActor] null
java.lang.NullPointerException
        at wherehows.common.utils.JobsUtil.getScheduledJobs(JobsUtil.java:88)
        at actors.SchedulerActor.runDueJobs(SchedulerActor.java:66)
        at actors.SchedulerActor.onReceive(SchedulerActor.java:47)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
